window.CASE_LOCAL_IMAGES = {
  "generatedAt": "2026-03-08T03:14:38.925Z",
  "source": "local-assets-cases-plus-bymykel-crates",
  "cases": {
    "Kilowatt Case": {
      "image": "assets/cases/kilowatt-case/weapons/001_Dual_Berettas_Hideout.png",
      "folder": "assets/cases/kilowatt-case",
      "csgContainerUrl": ""
    },
    "Revolution Case": {
      "image": "assets/cases/revolution-case/weapons/001_MAG-7_Insomnia.png",
      "folder": "assets/cases/revolution-case",
      "csgContainerUrl": ""
    },
    "Recoil Case": {
      "image": "assets/cases/recoil-case/weapons/001_FAMAS_Meow_36.png",
      "folder": "assets/cases/recoil-case",
      "csgContainerUrl": ""
    },
    "Dreams & Nightmares Case": {
      "image": "assets/cases/dreams-and-nightmares-case/weapons/001_Five-SeveN_Scrawl.png",
      "folder": "assets/cases/dreams-and-nightmares-case",
      "csgContainerUrl": ""
    },
    "Snakebite Case": {
      "image": "assets/cases/snakebite-case/weapons/001_SG_553_Heavy_Metal.png",
      "folder": "assets/cases/snakebite-case",
      "csgContainerUrl": ""
    },
    "Fracture Case": {
      "image": "assets/cases/fracture-case/weapons/001_Negev_Ultralight.png",
      "folder": "assets/cases/fracture-case",
      "csgContainerUrl": ""
    },
    "Prisma 2 Case": {
      "image": "assets/cases/prisma-2-case/weapons/001_AUG_Tom_Cat.png",
      "folder": "assets/cases/prisma-2-case",
      "csgContainerUrl": ""
    },
    "CS20 Case": {
      "image": "assets/cases/cs20-case/weapons/001_Dual_Berettas_Elite_1.6.png",
      "folder": "assets/cases/cs20-case",
      "csgContainerUrl": ""
    },
    "Prisma Case": {
      "image": "assets/cases/prisma-case/weapons/001_FAMAS_Crypsis.png",
      "folder": "assets/cases/prisma-case",
      "csgContainerUrl": ""
    },
    "Danger Zone Case": {
      "image": "assets/cases/danger-zone-case/weapons/001_MP9_Modest_Threat.png",
      "folder": "assets/cases/danger-zone-case",
      "csgContainerUrl": ""
    },
    "Horizon Case": {
      "image": "assets/cases/horizon-case/weapons/001_AUG_Amber_Slipstream.png",
      "folder": "assets/cases/horizon-case",
      "csgContainerUrl": ""
    },
    "Clutch Case": {
      "image": "assets/cases/clutch-case/weapons/001_PP-Bizon_Night_Riot.png",
      "folder": "assets/cases/clutch-case",
      "csgContainerUrl": ""
    },
    "Spectrum 2 Case": {
      "image": "assets/cases/spectrum-2-case/weapons/001_Sawed-Off_Morris.png",
      "folder": "assets/cases/spectrum-2-case",
      "csgContainerUrl": ""
    },
    "Spectrum Case": {
      "image": "assets/cases/spectrum-case/weapons/001_PP-Bizon_Jungle_Slipstream.png",
      "folder": "assets/cases/spectrum-case",
      "csgContainerUrl": ""
    },
    "Gamma 2 Case": {
      "image": "assets/cases/gamma-2-case/weapons/001_CZ75-Auto_Imprint.png",
      "folder": "assets/cases/gamma-2-case",
      "csgContainerUrl": ""
    },
    "Gamma Case": {
      "image": "assets/cases/gamma-case/weapons/001_Five-SeveN_Violent_Daimyo.png",
      "folder": "assets/cases/gamma-case",
      "csgContainerUrl": ""
    },
    "Chroma 3 Case": {
      "image": "assets/cases/chroma-3-case/weapons/001_Dual_Berettas_Ventilators.png",
      "folder": "assets/cases/chroma-3-case",
      "csgContainerUrl": ""
    },
    "Chroma 2 Case": {
      "image": "assets/cases/chroma-2-case/weapons/001_AK-47_Elite_Build.png",
      "folder": "assets/cases/chroma-2-case",
      "csgContainerUrl": ""
    },
    "Chroma Case": {
      "image": "assets/cases/chroma-case/weapons/001_Glock-18_Catacombs.png",
      "folder": "assets/cases/chroma-case",
      "csgContainerUrl": ""
    },
    "Falchion Case": {
      "image": "assets/cases/falchion-case/weapons/001_Galil_AR_Rocket_Pop.png",
      "folder": "assets/cases/falchion-case",
      "csgContainerUrl": ""
    },
    "Operation Wildfire Case": {
      "image": "assets/cases/operation-wildfire-case/weapons/001_PP-Bizon_Photic_Zone.png",
      "folder": "assets/cases/operation-wildfire-case",
      "csgContainerUrl": ""
    },
    "Operation Breakout Weapon Case": {
      "image": "assets/cases/operation-breakout-weapon-case/weapons/001_MP7_Urban_Hazard.png",
      "folder": "assets/cases/operation-breakout-weapon-case",
      "csgContainerUrl": ""
    },
    "Operation Vanguard Weapon Case": {
      "image": "assets/cases/operation-vanguard-weapon-case/weapons/001_G3SG1_Murky.png",
      "folder": "assets/cases/operation-vanguard-weapon-case",
      "csgContainerUrl": ""
    },
    "Operation Phoenix Weapon Case": {
      "image": "assets/cases/operation-phoenix-weapon-case/weapons/001_UMP-45_Corporal.png",
      "folder": "assets/cases/operation-phoenix-weapon-case",
      "csgContainerUrl": ""
    },
    "Huntsman Weapon Case": {
      "image": "assets/cases/huntsman-weapon-case/weapons/001_Tec-9_Isaac.png",
      "folder": "assets/cases/huntsman-weapon-case",
      "csgContainerUrl": ""
    }
  },
  "weapons": {
    "Dual Berettas | Hideout": "assets/cases/kilowatt-case/weapons/001_Dual_Berettas_Hideout.png",
    "MAC-10 | Light Box": "assets/cases/kilowatt-case/weapons/002_MAC-10_Light_Box.png",
    "Nova | Dark Sigil": "assets/cases/kilowatt-case/weapons/003_Nova_Dark_Sigil.png",
    "SSG 08 | Dezastre": "assets/cases/kilowatt-case/weapons/004_SSG_08_Dezastre.png",
    "Tec-9 | Slag": "assets/cases/kilowatt-case/weapons/005_Tec-9_Slag.png",
    "UMP-45 | Motorized": "assets/cases/kilowatt-case/weapons/006_UMP-45_Motorized.png",
    "XM1014 | Irezumi": "assets/cases/kilowatt-case/weapons/007_XM1014_Irezumi.png",
    "Glock-18 | Block-18": "assets/cases/kilowatt-case/weapons/008_Glock-18_Block-18.png",
    "M4A4 | Etch Lord": "assets/cases/kilowatt-case/weapons/009_M4A4_Etch_Lord.png",
    "Five-SeveN | Hybrid": "assets/cases/kilowatt-case/weapons/010_Five-SeveN_Hybrid.png",
    "MP7 | Just Smile": "assets/cases/kilowatt-case/weapons/011_MP7_Just_Smile.png",
    "Sawed-Off | Analog Input": "assets/cases/kilowatt-case/weapons/012_Sawed-Off_Analog_Input.png",
    "M4A1-S | Black Lotus": "assets/cases/kilowatt-case/weapons/013_M4A1-S_Black_Lotus.png",
    "Zeus x27 | Olympus": "assets/cases/kilowatt-case/weapons/014_Zeus_x27_Olympus.png",
    "USP-S | Jawbreaker": "assets/cases/kilowatt-case/weapons/015_USP-S_Jawbreaker.png",
    "AWP | Chrome Cannon": "assets/cases/kilowatt-case/weapons/016_AWP_Chrome_Cannon.png",
    "AK-47 | Inheritance": "assets/cases/kilowatt-case/weapons/017_AK-47_Inheritance.png",
    "★ Kukri Knife": "assets/cases/kilowatt-case/weapons/018_%E2%98%85_Kukri_Knife.png",
    "★ Kukri Knife | Fade": "assets/cases/kilowatt-case/weapons/019_%E2%98%85_Kukri_Knife_Fade.png",
    "★ Kukri Knife | Slaughter": "assets/cases/kilowatt-case/weapons/020_%E2%98%85_Kukri_Knife_Slaughter.png",
    "★ Kukri Knife | Blue Steel": "assets/cases/kilowatt-case/weapons/021_%E2%98%85_Kukri_Knife_Blue_Steel.png",
    "★ Kukri Knife | Stained": "assets/cases/kilowatt-case/weapons/022_%E2%98%85_Kukri_Knife_Stained.png",
    "★ Kukri Knife | Case Hardened": "assets/cases/kilowatt-case/weapons/023_%E2%98%85_Kukri_Knife_Case_Hardened.png",
    "★ Kukri Knife | Forest DDPAT": "assets/cases/kilowatt-case/weapons/024_%E2%98%85_Kukri_Knife_Forest_DDPAT.png",
    "★ Kukri Knife | Boreal Forest": "assets/cases/kilowatt-case/weapons/025_%E2%98%85_Kukri_Knife_Boreal_Forest.png",
    "★ Kukri Knife | Crimson Web": "assets/cases/kilowatt-case/weapons/026_%E2%98%85_Kukri_Knife_Crimson_Web.png",
    "★ Kukri Knife | Scorched": "assets/cases/kilowatt-case/weapons/027_%E2%98%85_Kukri_Knife_Scorched.png",
    "★ Kukri Knife | Safari Mesh": "assets/cases/kilowatt-case/weapons/028_%E2%98%85_Kukri_Knife_Safari_Mesh.png",
    "★ Kukri Knife | Night Stripe": "assets/cases/kilowatt-case/weapons/029_%E2%98%85_Kukri_Knife_Night_Stripe.png",
    "★ Kukri Knife | Urban Masked": "assets/cases/kilowatt-case/weapons/030_%E2%98%85_Kukri_Knife_Urban_Masked.png",
    "MAG-7 | Insomnia": "assets/cases/revolution-case/weapons/001_MAG-7_Insomnia.png",
    "MP9 | Featherweight": "assets/cases/revolution-case/weapons/002_MP9_Featherweight.png",
    "SCAR-20 | Fragments": "assets/cases/revolution-case/weapons/003_SCAR-20_Fragments.png",
    "P250 | Re.built": "assets/cases/revolution-case/weapons/004_P250_Re.built.png",
    "MP5-SD | Liquidation": "assets/cases/revolution-case/weapons/005_MP5-SD_Liquidation.png",
    "SG 553 | Cyberforce": "assets/cases/revolution-case/weapons/006_SG_553_Cyberforce.png",
    "Tec-9 | Rebel": "assets/cases/revolution-case/weapons/007_Tec-9_Rebel.png",
    "M4A1-S | Emphorosaur-S": "assets/cases/revolution-case/weapons/008_M4A1-S_Emphorosaur-S.png",
    "Glock-18 | Umbral Rabbit": "assets/cases/revolution-case/weapons/009_Glock-18_Umbral_Rabbit.png",
    "MAC-10 | Sakkaku": "assets/cases/revolution-case/weapons/010_MAC-10_Sakkaku.png",
    "R8 Revolver | Banana Cannon": "assets/cases/revolution-case/weapons/011_R8_Revolver_Banana_Cannon.png",
    "P90 | Neoqueen": "assets/cases/revolution-case/weapons/012_P90_Neoqueen.png",
    "AWP | Duality": "assets/cases/revolution-case/weapons/013_AWP_Duality.png",
    "UMP-45 | Wild Child": "assets/cases/revolution-case/weapons/014_UMP-45_Wild_Child.png",
    "P2000 | Wicked Sick": "assets/cases/revolution-case/weapons/015_P2000_Wicked_Sick.png",
    "M4A4 | Temukau": "assets/cases/revolution-case/weapons/016_M4A4_Temukau.png",
    "AK-47 | Head Shot": "assets/cases/revolution-case/weapons/017_AK-47_Head_Shot.png",
    "★ Driver Gloves | Imperial Plaid": "assets/cases/clutch-case/weapons/018_%E2%98%85_Driver_Gloves_Imperial_Plaid.png",
    "★ Driver Gloves | King Snake": "assets/cases/clutch-case/weapons/019_%E2%98%85_Driver_Gloves_King_Snake.png",
    "★ Driver Gloves | Racing Green": "assets/cases/clutch-case/weapons/020_%E2%98%85_Driver_Gloves_Racing_Green.png",
    "★ Driver Gloves | Overtake": "assets/cases/clutch-case/weapons/021_%E2%98%85_Driver_Gloves_Overtake.png",
    "★ Hand Wraps | Cobalt Skulls": "assets/cases/clutch-case/weapons/022_%E2%98%85_Hand_Wraps_Cobalt_Skulls.png",
    "★ Hand Wraps | Overprint": "assets/cases/clutch-case/weapons/023_%E2%98%85_Hand_Wraps_Overprint.png",
    "★ Hand Wraps | Arboreal": "assets/cases/clutch-case/weapons/024_%E2%98%85_Hand_Wraps_Arboreal.png",
    "★ Hand Wraps | Duct Tape": "assets/cases/clutch-case/weapons/025_%E2%98%85_Hand_Wraps_Duct_Tape.png",
    "★ Hydra Gloves | Case Hardened": "assets/cases/clutch-case/weapons/026_%E2%98%85_Hydra_Gloves_Case_Hardened.png",
    "★ Hydra Gloves | Emerald": "assets/cases/clutch-case/weapons/027_%E2%98%85_Hydra_Gloves_Emerald.png",
    "★ Hydra Gloves | Rattler": "assets/cases/clutch-case/weapons/028_%E2%98%85_Hydra_Gloves_Rattler.png",
    "★ Hydra Gloves | Mangrove": "assets/cases/clutch-case/weapons/029_%E2%98%85_Hydra_Gloves_Mangrove.png",
    "★ Moto Gloves | POW!": "assets/cases/clutch-case/weapons/030_%E2%98%85_Moto_Gloves_POW!.png",
    "★ Moto Gloves | Polygon": "assets/cases/clutch-case/weapons/031_%E2%98%85_Moto_Gloves_Polygon.png",
    "★ Moto Gloves | Turtle": "assets/cases/clutch-case/weapons/032_%E2%98%85_Moto_Gloves_Turtle.png",
    "★ Moto Gloves | Transport": "assets/cases/clutch-case/weapons/033_%E2%98%85_Moto_Gloves_Transport.png",
    "★ Specialist Gloves | Crimson Web": "assets/cases/clutch-case/weapons/034_%E2%98%85_Specialist_Gloves_Crimson_Web.png",
    "★ Specialist Gloves | Mogul": "assets/cases/clutch-case/weapons/035_%E2%98%85_Specialist_Gloves_Mogul.png",
    "★ Specialist Gloves | Fade": "assets/cases/clutch-case/weapons/036_%E2%98%85_Specialist_Gloves_Fade.png",
    "★ Specialist Gloves | Buckshot": "assets/cases/clutch-case/weapons/037_%E2%98%85_Specialist_Gloves_Buckshot.png",
    "★ Sport Gloves | Vice": "assets/cases/clutch-case/weapons/038_%E2%98%85_Sport_Gloves_Vice.png",
    "★ Sport Gloves | Amphibious": "assets/cases/clutch-case/weapons/039_%E2%98%85_Sport_Gloves_Amphibious.png",
    "★ Sport Gloves | Omega": "assets/cases/clutch-case/weapons/040_%E2%98%85_Sport_Gloves_Omega.png",
    "★ Sport Gloves | Bronze Morph": "assets/cases/clutch-case/weapons/041_%E2%98%85_Sport_Gloves_Bronze_Morph.png",
    "FAMAS | Meow 36": "assets/cases/recoil-case/weapons/001_FAMAS_Meow_36.png",
    "Galil AR | Destroyer": "assets/cases/recoil-case/weapons/002_Galil_AR_Destroyer.png",
    "M4A4 | Poly Mag": "assets/cases/recoil-case/weapons/003_M4A4_Poly_Mag.png",
    "MAC-10 | Monkeyflage": "assets/cases/recoil-case/weapons/004_MAC-10_Monkeyflage.png",
    "Negev | Drop Me": "assets/cases/recoil-case/weapons/005_Negev_Drop_Me.png",
    "UMP-45 | Roadblock": "assets/cases/recoil-case/weapons/006_UMP-45_Roadblock.png",
    "Glock-18 | Winterized": "assets/cases/recoil-case/weapons/007_Glock-18_Winterized.png",
    "R8 Revolver | Crazy 8": "assets/cases/recoil-case/weapons/008_R8_Revolver_Crazy_8.png",
    "M249 | Downtown": "assets/cases/recoil-case/weapons/009_M249_Downtown.png",
    "SG 553 | Dragon Tech": "assets/cases/recoil-case/weapons/010_SG_553_Dragon_Tech.png",
    "P90 | Vent Rush": "assets/cases/recoil-case/weapons/011_P90_Vent_Rush.png",
    "Dual Berettas | Flora Carnivora": "assets/cases/recoil-case/weapons/012_Dual_Berettas_Flora_Carnivora.png",
    "AK-47 | Ice Coaled": "assets/cases/recoil-case/weapons/013_AK-47_Ice_Coaled.png",
    "P250 | Visions": "assets/cases/recoil-case/weapons/014_P250_Visions.png",
    "Sawed-Off | Kiss♥Love": "assets/cases/recoil-case/weapons/015_Sawed-Off_Kiss%E2%99%A5Love.png",
    "USP-S | Printstream": "assets/cases/recoil-case/weapons/016_USP-S_Printstream.png",
    "AWP | Chromatic Aberration": "assets/cases/recoil-case/weapons/017_AWP_Chromatic_Aberration.png",
    "★ Broken Fang Gloves | Yellow-banded": "assets/cases/snakebite-case/weapons/018_%E2%98%85_Broken_Fang_Gloves_Yellow-banded.png",
    "★ Broken Fang Gloves | Unhinged": "assets/cases/snakebite-case/weapons/019_%E2%98%85_Broken_Fang_Gloves_Unhinged.png",
    "★ Broken Fang Gloves | Needle Point": "assets/cases/snakebite-case/weapons/020_%E2%98%85_Broken_Fang_Gloves_Needle_Point.png",
    "★ Broken Fang Gloves | Jade": "assets/cases/snakebite-case/weapons/021_%E2%98%85_Broken_Fang_Gloves_Jade.png",
    "★ Driver Gloves | Snow Leopard": "assets/cases/snakebite-case/weapons/022_%E2%98%85_Driver_Gloves_Snow_Leopard.png",
    "★ Driver Gloves | Black Tie": "assets/cases/snakebite-case/weapons/023_%E2%98%85_Driver_Gloves_Black_Tie.png",
    "★ Driver Gloves | Rezan the Red": "assets/cases/snakebite-case/weapons/024_%E2%98%85_Driver_Gloves_Rezan_the_Red.png",
    "★ Driver Gloves | Queen Jaguar": "assets/cases/snakebite-case/weapons/025_%E2%98%85_Driver_Gloves_Queen_Jaguar.png",
    "★ Hand Wraps | CAUTION!": "assets/cases/snakebite-case/weapons/026_%E2%98%85_Hand_Wraps_CAUTION!.png",
    "★ Hand Wraps | Giraffe": "assets/cases/snakebite-case/weapons/027_%E2%98%85_Hand_Wraps_Giraffe.png",
    "★ Hand Wraps | Constrictor": "assets/cases/snakebite-case/weapons/028_%E2%98%85_Hand_Wraps_Constrictor.png",
    "★ Hand Wraps | Desert Shamagh": "assets/cases/snakebite-case/weapons/029_%E2%98%85_Hand_Wraps_Desert_Shamagh.png",
    "★ Moto Gloves | Blood Pressure": "assets/cases/snakebite-case/weapons/030_%E2%98%85_Moto_Gloves_Blood_Pressure.png",
    "★ Moto Gloves | Smoke Out": "assets/cases/snakebite-case/weapons/031_%E2%98%85_Moto_Gloves_Smoke_Out.png",
    "★ Moto Gloves | Finish Line": "assets/cases/snakebite-case/weapons/032_%E2%98%85_Moto_Gloves_Finish_Line.png",
    "★ Moto Gloves | 3rd Commando Company": "assets/cases/snakebite-case/weapons/033_%E2%98%85_Moto_Gloves_3rd_Commando_Company.png",
    "★ Specialist Gloves | Field Agent": "assets/cases/snakebite-case/weapons/034_%E2%98%85_Specialist_Gloves_Field_Agent.png",
    "★ Specialist Gloves | Tiger Strike": "assets/cases/snakebite-case/weapons/035_%E2%98%85_Specialist_Gloves_Tiger_Strike.png",
    "★ Specialist Gloves | Lt. Commander": "assets/cases/snakebite-case/weapons/036_%E2%98%85_Specialist_Gloves_Lt._Commander.png",
    "★ Specialist Gloves | Marble Fade": "assets/cases/snakebite-case/weapons/037_%E2%98%85_Specialist_Gloves_Marble_Fade.png",
    "★ Sport Gloves | Slingshot": "assets/cases/snakebite-case/weapons/038_%E2%98%85_Sport_Gloves_Slingshot.png",
    "★ Sport Gloves | Scarlet Shamagh": "assets/cases/snakebite-case/weapons/039_%E2%98%85_Sport_Gloves_Scarlet_Shamagh.png",
    "★ Sport Gloves | Nocts": "assets/cases/snakebite-case/weapons/040_%E2%98%85_Sport_Gloves_Nocts.png",
    "★ Sport Gloves | Big Game": "assets/cases/snakebite-case/weapons/041_%E2%98%85_Sport_Gloves_Big_Game.png",
    "Five-SeveN | Scrawl": "assets/cases/dreams-and-nightmares-case/weapons/001_Five-SeveN_Scrawl.png",
    "MAC-10 | Ensnared": "assets/cases/dreams-and-nightmares-case/weapons/002_MAC-10_Ensnared.png",
    "MAG-7 | Foresight": "assets/cases/dreams-and-nightmares-case/weapons/003_MAG-7_Foresight.png",
    "MP5-SD | Necro Jr.": "assets/cases/dreams-and-nightmares-case/weapons/004_MP5-SD_Necro_Jr..png",
    "P2000 | Lifted Spirits": "assets/cases/dreams-and-nightmares-case/weapons/005_P2000_Lifted_Spirits.png",
    "SCAR-20 | Poultrygeist": "assets/cases/dreams-and-nightmares-case/weapons/006_SCAR-20_Poultrygeist.png",
    "Sawed-Off | Spirit Board": "assets/cases/dreams-and-nightmares-case/weapons/007_Sawed-Off_Spirit_Board.png",
    "PP-Bizon | Space Cat": "assets/cases/dreams-and-nightmares-case/weapons/008_PP-Bizon_Space_Cat.png",
    "G3SG1 | Dream Glade": "assets/cases/dreams-and-nightmares-case/weapons/009_G3SG1_Dream_Glade.png",
    "M4A1-S | Night Terror": "assets/cases/dreams-and-nightmares-case/weapons/010_M4A1-S_Night_Terror.png",
    "XM1014 | Zombie Offensive": "assets/cases/dreams-and-nightmares-case/weapons/011_XM1014_Zombie_Offensive.png",
    "USP-S | Ticket to Hell": "assets/cases/dreams-and-nightmares-case/weapons/012_USP-S_Ticket_to_Hell.png",
    "Dual Berettas | Melondrama": "assets/cases/dreams-and-nightmares-case/weapons/013_Dual_Berettas_Melondrama.png",
    "FAMAS | Rapid Eye Movement": "assets/cases/dreams-and-nightmares-case/weapons/014_FAMAS_Rapid_Eye_Movement.png",
    "MP7 | Abyssal Apparition": "assets/cases/dreams-and-nightmares-case/weapons/015_MP7_Abyssal_Apparition.png",
    "AK-47 | Nightwish": "assets/cases/dreams-and-nightmares-case/weapons/016_AK-47_Nightwish.png",
    "MP9 | Starlight Protector": "assets/cases/dreams-and-nightmares-case/weapons/017_MP9_Starlight_Protector.png",
    "★ Bowie Knife | Gamma Doppler": "assets/cases/dreams-and-nightmares-case/weapons/022_%E2%98%85_Bowie_Knife_Gamma_Doppler.png",
    "★ Bowie Knife | Lore": "assets/cases/dreams-and-nightmares-case/weapons/023_%E2%98%85_Bowie_Knife_Lore.png",
    "★ Bowie Knife | Autotronic": "assets/cases/dreams-and-nightmares-case/weapons/024_%E2%98%85_Bowie_Knife_Autotronic.png",
    "★ Bowie Knife | Black Laminate": "assets/cases/dreams-and-nightmares-case/weapons/025_%E2%98%85_Bowie_Knife_Black_Laminate.png",
    "★ Bowie Knife | Freehand": "assets/cases/dreams-and-nightmares-case/weapons/026_%E2%98%85_Bowie_Knife_Freehand.png",
    "★ Bowie Knife | Bright Water": "assets/cases/dreams-and-nightmares-case/weapons/027_%E2%98%85_Bowie_Knife_Bright_Water.png",
    "★ Butterfly Knife | Gamma Doppler": "assets/cases/dreams-and-nightmares-case/weapons/032_%E2%98%85_Butterfly_Knife_Gamma_Doppler.png",
    "★ Butterfly Knife | Lore": "assets/cases/dreams-and-nightmares-case/weapons/033_%E2%98%85_Butterfly_Knife_Lore.png",
    "★ Butterfly Knife | Autotronic": "assets/cases/dreams-and-nightmares-case/weapons/034_%E2%98%85_Butterfly_Knife_Autotronic.png",
    "★ Butterfly Knife | Black Laminate": "assets/cases/dreams-and-nightmares-case/weapons/035_%E2%98%85_Butterfly_Knife_Black_Laminate.png",
    "★ Butterfly Knife | Freehand": "assets/cases/dreams-and-nightmares-case/weapons/036_%E2%98%85_Butterfly_Knife_Freehand.png",
    "★ Butterfly Knife | Bright Water": "assets/cases/dreams-and-nightmares-case/weapons/037_%E2%98%85_Butterfly_Knife_Bright_Water.png",
    "★ Falchion Knife | Gamma Doppler": "assets/cases/dreams-and-nightmares-case/weapons/042_%E2%98%85_Falchion_Knife_Gamma_Doppler.png",
    "★ Falchion Knife | Lore": "assets/cases/dreams-and-nightmares-case/weapons/043_%E2%98%85_Falchion_Knife_Lore.png",
    "★ Falchion Knife | Autotronic": "assets/cases/dreams-and-nightmares-case/weapons/044_%E2%98%85_Falchion_Knife_Autotronic.png",
    "★ Falchion Knife | Black Laminate": "assets/cases/dreams-and-nightmares-case/weapons/045_%E2%98%85_Falchion_Knife_Black_Laminate.png",
    "★ Falchion Knife | Freehand": "assets/cases/dreams-and-nightmares-case/weapons/046_%E2%98%85_Falchion_Knife_Freehand.png",
    "★ Falchion Knife | Bright Water": "assets/cases/dreams-and-nightmares-case/weapons/047_%E2%98%85_Falchion_Knife_Bright_Water.png",
    "★ Huntsman Knife | Gamma Doppler": "assets/cases/dreams-and-nightmares-case/weapons/052_%E2%98%85_Huntsman_Knife_Gamma_Doppler.png",
    "★ Huntsman Knife | Lore": "assets/cases/dreams-and-nightmares-case/weapons/053_%E2%98%85_Huntsman_Knife_Lore.png",
    "★ Huntsman Knife | Autotronic": "assets/cases/dreams-and-nightmares-case/weapons/054_%E2%98%85_Huntsman_Knife_Autotronic.png",
    "★ Huntsman Knife | Black Laminate": "assets/cases/dreams-and-nightmares-case/weapons/055_%E2%98%85_Huntsman_Knife_Black_Laminate.png",
    "★ Huntsman Knife | Freehand": "assets/cases/dreams-and-nightmares-case/weapons/056_%E2%98%85_Huntsman_Knife_Freehand.png",
    "★ Huntsman Knife | Bright Water": "assets/cases/dreams-and-nightmares-case/weapons/057_%E2%98%85_Huntsman_Knife_Bright_Water.png",
    "★ Shadow Daggers | Gamma Doppler": "assets/cases/dreams-and-nightmares-case/weapons/062_%E2%98%85_Shadow_Daggers_Gamma_Doppler.png",
    "★ Shadow Daggers | Lore": "assets/cases/dreams-and-nightmares-case/weapons/063_%E2%98%85_Shadow_Daggers_Lore.png",
    "★ Shadow Daggers | Autotronic": "assets/cases/dreams-and-nightmares-case/weapons/064_%E2%98%85_Shadow_Daggers_Autotronic.png",
    "★ Shadow Daggers | Black Laminate": "assets/cases/dreams-and-nightmares-case/weapons/065_%E2%98%85_Shadow_Daggers_Black_Laminate.png",
    "★ Shadow Daggers | Freehand": "assets/cases/dreams-and-nightmares-case/weapons/066_%E2%98%85_Shadow_Daggers_Freehand.png",
    "★ Shadow Daggers | Bright Water": "assets/cases/dreams-and-nightmares-case/weapons/067_%E2%98%85_Shadow_Daggers_Bright_Water.png",
    "SG 553 | Heavy Metal": "assets/cases/snakebite-case/weapons/001_SG_553_Heavy_Metal.png",
    "Glock-18 | Clear Polymer": "assets/cases/snakebite-case/weapons/002_Glock-18_Clear_Polymer.png",
    "M249 | O.S.I.P.R.": "assets/cases/snakebite-case/weapons/003_M249_O.S.I.P.R..png",
    "CZ75-Auto | Circaetus": "assets/cases/snakebite-case/weapons/004_CZ75-Auto_Circaetus.png",
    "UMP-45 | Oscillator": "assets/cases/snakebite-case/weapons/005_UMP-45_Oscillator.png",
    "R8 Revolver | Junk Yard": "assets/cases/snakebite-case/weapons/006_R8_Revolver_Junk_Yard.png",
    "Nova | Windblown": "assets/cases/snakebite-case/weapons/007_Nova_Windblown.png",
    "P250 | Cyber Shell": "assets/cases/snakebite-case/weapons/008_P250_Cyber_Shell.png",
    "Negev | dev_texture": "assets/cases/snakebite-case/weapons/009_Negev_dev_texture.png",
    "MAC-10 | Button Masher": "assets/cases/snakebite-case/weapons/010_MAC-10_Button_Masher.png",
    "Desert Eagle | Trigger Discipline": "assets/cases/snakebite-case/weapons/011_Desert_Eagle_Trigger_Discipline.png",
    "AK-47 | Slate": "assets/cases/snakebite-case/weapons/012_AK-47_Slate.png",
    "MP9 | Food Chain": "assets/cases/snakebite-case/weapons/013_MP9_Food_Chain.png",
    "XM1014 | XOXO": "assets/cases/snakebite-case/weapons/014_XM1014_XOXO.png",
    "Galil AR | Chromatic Aberration": "assets/cases/snakebite-case/weapons/015_Galil_AR_Chromatic_Aberration.png",
    "USP-S | The Traitor": "assets/cases/snakebite-case/weapons/016_USP-S_The_Traitor.png",
    "M4A4 | In Living Color": "assets/cases/snakebite-case/weapons/017_M4A4_In_Living_Color.png",
    "Negev | Ultralight": "assets/cases/fracture-case/weapons/001_Negev_Ultralight.png",
    "P2000 | Gnarled": "assets/cases/fracture-case/weapons/002_P2000_Gnarled.png",
    "SG 553 | Ol' Rusty": "assets/cases/fracture-case/weapons/003_SG_553_Ol'_Rusty.png",
    "SSG 08 | Mainframe 001": "assets/cases/fracture-case/weapons/004_SSG_08_Mainframe_001.png",
    "P250 | Cassette": "assets/cases/fracture-case/weapons/005_P250_Cassette.png",
    "P90 | Freight": "assets/cases/fracture-case/weapons/006_P90_Freight.png",
    "PP-Bizon | Runic": "assets/cases/fracture-case/weapons/007_PP-Bizon_Runic.png",
    "MAG-7 | Monster Call": "assets/cases/fracture-case/weapons/008_MAG-7_Monster_Call.png",
    "Tec-9 | Brother": "assets/cases/fracture-case/weapons/009_Tec-9_Brother.png",
    "MAC-10 | Allure": "assets/cases/fracture-case/weapons/010_MAC-10_Allure.png",
    "Galil AR | Connexion": "assets/cases/fracture-case/weapons/011_Galil_AR_Connexion.png",
    "MP5-SD | Kitbash": "assets/cases/fracture-case/weapons/012_MP5-SD_Kitbash.png",
    "M4A4 | Tooth Fairy": "assets/cases/fracture-case/weapons/013_M4A4_Tooth_Fairy.png",
    "Glock-18 | Vogue": "assets/cases/fracture-case/weapons/014_Glock-18_Vogue.png",
    "XM1014 | Entombed": "assets/cases/fracture-case/weapons/015_XM1014_Entombed.png",
    "Desert Eagle | Printstream": "assets/cases/fracture-case/weapons/016_Desert_Eagle_Printstream.png",
    "AK-47 | Legion of Anubis": "assets/cases/fracture-case/weapons/017_AK-47_Legion_of_Anubis.png",
    "★ Nomad Knife": "assets/cases/fracture-case/weapons/018_%E2%98%85_Nomad_Knife.png",
    "★ Nomad Knife | Fade": "assets/cases/fracture-case/weapons/019_%E2%98%85_Nomad_Knife_Fade.png",
    "★ Nomad Knife | Crimson Web": "assets/cases/fracture-case/weapons/020_%E2%98%85_Nomad_Knife_Crimson_Web.png",
    "★ Nomad Knife | Slaughter": "assets/cases/fracture-case/weapons/021_%E2%98%85_Nomad_Knife_Slaughter.png",
    "★ Nomad Knife | Case Hardened": "assets/cases/fracture-case/weapons/022_%E2%98%85_Nomad_Knife_Case_Hardened.png",
    "★ Nomad Knife | Urban Masked": "assets/cases/fracture-case/weapons/023_%E2%98%85_Nomad_Knife_Urban_Masked.png",
    "★ Nomad Knife | Blue Steel": "assets/cases/fracture-case/weapons/024_%E2%98%85_Nomad_Knife_Blue_Steel.png",
    "★ Nomad Knife | Night Stripe": "assets/cases/fracture-case/weapons/025_%E2%98%85_Nomad_Knife_Night_Stripe.png",
    "★ Nomad Knife | Stained": "assets/cases/fracture-case/weapons/026_%E2%98%85_Nomad_Knife_Stained.png",
    "★ Nomad Knife | Forest DDPAT": "assets/cases/fracture-case/weapons/027_%E2%98%85_Nomad_Knife_Forest_DDPAT.png",
    "★ Nomad Knife | Boreal Forest": "assets/cases/fracture-case/weapons/028_%E2%98%85_Nomad_Knife_Boreal_Forest.png",
    "★ Nomad Knife | Scorched": "assets/cases/fracture-case/weapons/029_%E2%98%85_Nomad_Knife_Scorched.png",
    "★ Nomad Knife | Safari Mesh": "assets/cases/fracture-case/weapons/030_%E2%98%85_Nomad_Knife_Safari_Mesh.png",
    "★ Paracord Knife": "assets/cases/fracture-case/weapons/031_%E2%98%85_Paracord_Knife.png",
    "★ Paracord Knife | Fade": "assets/cases/fracture-case/weapons/032_%E2%98%85_Paracord_Knife_Fade.png",
    "★ Paracord Knife | Crimson Web": "assets/cases/fracture-case/weapons/033_%E2%98%85_Paracord_Knife_Crimson_Web.png",
    "★ Paracord Knife | Slaughter": "assets/cases/fracture-case/weapons/034_%E2%98%85_Paracord_Knife_Slaughter.png",
    "★ Paracord Knife | Case Hardened": "assets/cases/fracture-case/weapons/035_%E2%98%85_Paracord_Knife_Case_Hardened.png",
    "★ Paracord Knife | Urban Masked": "assets/cases/fracture-case/weapons/036_%E2%98%85_Paracord_Knife_Urban_Masked.png",
    "★ Paracord Knife | Blue Steel": "assets/cases/fracture-case/weapons/037_%E2%98%85_Paracord_Knife_Blue_Steel.png",
    "★ Paracord Knife | Night Stripe": "assets/cases/fracture-case/weapons/038_%E2%98%85_Paracord_Knife_Night_Stripe.png",
    "★ Paracord Knife | Stained": "assets/cases/fracture-case/weapons/039_%E2%98%85_Paracord_Knife_Stained.png",
    "★ Paracord Knife | Forest DDPAT": "assets/cases/fracture-case/weapons/040_%E2%98%85_Paracord_Knife_Forest_DDPAT.png",
    "★ Paracord Knife | Boreal Forest": "assets/cases/fracture-case/weapons/041_%E2%98%85_Paracord_Knife_Boreal_Forest.png",
    "★ Paracord Knife | Scorched": "assets/cases/fracture-case/weapons/042_%E2%98%85_Paracord_Knife_Scorched.png",
    "★ Paracord Knife | Safari Mesh": "assets/cases/fracture-case/weapons/043_%E2%98%85_Paracord_Knife_Safari_Mesh.png",
    "★ Skeleton Knife": "assets/cases/fracture-case/weapons/044_%E2%98%85_Skeleton_Knife.png",
    "★ Skeleton Knife | Fade": "assets/cases/fracture-case/weapons/045_%E2%98%85_Skeleton_Knife_Fade.png",
    "★ Skeleton Knife | Crimson Web": "assets/cases/fracture-case/weapons/046_%E2%98%85_Skeleton_Knife_Crimson_Web.png",
    "★ Skeleton Knife | Slaughter": "assets/cases/fracture-case/weapons/047_%E2%98%85_Skeleton_Knife_Slaughter.png",
    "★ Skeleton Knife | Case Hardened": "assets/cases/fracture-case/weapons/048_%E2%98%85_Skeleton_Knife_Case_Hardened.png",
    "★ Skeleton Knife | Urban Masked": "assets/cases/fracture-case/weapons/049_%E2%98%85_Skeleton_Knife_Urban_Masked.png",
    "★ Skeleton Knife | Blue Steel": "assets/cases/fracture-case/weapons/050_%E2%98%85_Skeleton_Knife_Blue_Steel.png",
    "★ Skeleton Knife | Night Stripe": "assets/cases/fracture-case/weapons/051_%E2%98%85_Skeleton_Knife_Night_Stripe.png",
    "★ Skeleton Knife | Stained": "assets/cases/fracture-case/weapons/052_%E2%98%85_Skeleton_Knife_Stained.png",
    "★ Skeleton Knife | Forest DDPAT": "assets/cases/fracture-case/weapons/053_%E2%98%85_Skeleton_Knife_Forest_DDPAT.png",
    "★ Skeleton Knife | Boreal Forest": "assets/cases/fracture-case/weapons/054_%E2%98%85_Skeleton_Knife_Boreal_Forest.png",
    "★ Skeleton Knife | Scorched": "assets/cases/fracture-case/weapons/055_%E2%98%85_Skeleton_Knife_Scorched.png",
    "★ Skeleton Knife | Safari Mesh": "assets/cases/fracture-case/weapons/056_%E2%98%85_Skeleton_Knife_Safari_Mesh.png",
    "★ Survival Knife": "assets/cases/fracture-case/weapons/057_%E2%98%85_Survival_Knife.png",
    "★ Survival Knife | Fade": "assets/cases/fracture-case/weapons/058_%E2%98%85_Survival_Knife_Fade.png",
    "★ Survival Knife | Crimson Web": "assets/cases/fracture-case/weapons/059_%E2%98%85_Survival_Knife_Crimson_Web.png",
    "★ Survival Knife | Slaughter": "assets/cases/fracture-case/weapons/060_%E2%98%85_Survival_Knife_Slaughter.png",
    "★ Survival Knife | Case Hardened": "assets/cases/fracture-case/weapons/061_%E2%98%85_Survival_Knife_Case_Hardened.png",
    "★ Survival Knife | Urban Masked": "assets/cases/fracture-case/weapons/062_%E2%98%85_Survival_Knife_Urban_Masked.png",
    "★ Survival Knife | Blue Steel": "assets/cases/fracture-case/weapons/063_%E2%98%85_Survival_Knife_Blue_Steel.png",
    "★ Survival Knife | Night Stripe": "assets/cases/fracture-case/weapons/064_%E2%98%85_Survival_Knife_Night_Stripe.png",
    "★ Survival Knife | Stained": "assets/cases/fracture-case/weapons/065_%E2%98%85_Survival_Knife_Stained.png",
    "★ Survival Knife | Forest DDPAT": "assets/cases/fracture-case/weapons/066_%E2%98%85_Survival_Knife_Forest_DDPAT.png",
    "★ Survival Knife | Boreal Forest": "assets/cases/fracture-case/weapons/067_%E2%98%85_Survival_Knife_Boreal_Forest.png",
    "★ Survival Knife | Scorched": "assets/cases/fracture-case/weapons/068_%E2%98%85_Survival_Knife_Scorched.png",
    "★ Survival Knife | Safari Mesh": "assets/cases/fracture-case/weapons/069_%E2%98%85_Survival_Knife_Safari_Mesh.png",
    "AUG | Tom Cat": "assets/cases/prisma-2-case/weapons/001_AUG_Tom_Cat.png",
    "AWP | Capillary": "assets/cases/prisma-2-case/weapons/002_AWP_Capillary.png",
    "CZ75-Auto | Distressed": "assets/cases/prisma-2-case/weapons/003_CZ75-Auto_Distressed.png",
    "Desert Eagle | Blue Ply": "assets/cases/prisma-2-case/weapons/004_Desert_Eagle_Blue_Ply.png",
    "MP5-SD | Desert Strike": "assets/cases/prisma-2-case/weapons/005_MP5-SD_Desert_Strike.png",
    "Negev | Prototype": "assets/cases/prisma-2-case/weapons/006_Negev_Prototype.png",
    "R8 Revolver | Bone Forged": "assets/cases/prisma-2-case/weapons/007_R8_Revolver_Bone_Forged.png",
    "P2000 | Acid Etched": "assets/cases/prisma-2-case/weapons/008_P2000_Acid_Etched.png",
    "Sawed-Off | Apocalypto": "assets/cases/prisma-2-case/weapons/009_Sawed-Off_Apocalypto.png",
    "SCAR-20 | Enforcer": "assets/cases/prisma-2-case/weapons/010_SCAR-20_Enforcer.png",
    "SG 553 | Darkwing": "assets/cases/prisma-2-case/weapons/011_SG_553_Darkwing.png",
    "SSG 08 | Fever Dream": "assets/cases/prisma-2-case/weapons/012_SSG_08_Fever_Dream.png",
    "AK-47 | Phantom Disruptor": "assets/cases/prisma-2-case/weapons/013_AK-47_Phantom_Disruptor.png",
    "MAC-10 | Disco Tech": "assets/cases/prisma-2-case/weapons/014_MAC-10_Disco_Tech.png",
    "MAG-7 | Justice": "assets/cases/prisma-2-case/weapons/015_MAG-7_Justice.png",
    "M4A1-S | Player Two": "assets/cases/prisma-2-case/weapons/016_M4A1-S_Player_Two.png",
    "Glock-18 | Bullet Queen": "assets/cases/prisma-2-case/weapons/017_Glock-18_Bullet_Queen.png",
    "★ Navaja Knife": "assets/cases/horizon-case/weapons/018_%E2%98%85_Navaja_Knife.png",
    "★ Navaja Knife | Marble Fade": "assets/cases/prisma-case/weapons/019_%E2%98%85_Navaja_Knife_Marble_Fade.png",
    "★ Navaja Knife | Tiger Tooth": "assets/cases/prisma-case/weapons/020_%E2%98%85_Navaja_Knife_Tiger_Tooth.png",
    "★ Navaja Knife | Doppler": "assets/cases/prisma-case/weapons/027_%E2%98%85_Navaja_Knife_Doppler.png",
    "★ Navaja Knife | Damascus Steel": "assets/cases/prisma-case/weapons/028_%E2%98%85_Navaja_Knife_Damascus_Steel.png",
    "★ Navaja Knife | Ultraviolet": "assets/cases/prisma-case/weapons/029_%E2%98%85_Navaja_Knife_Ultraviolet.png",
    "★ Navaja Knife | Rust Coat": "assets/cases/prisma-case/weapons/030_%E2%98%85_Navaja_Knife_Rust_Coat.png",
    "★ Stiletto Knife": "assets/cases/horizon-case/weapons/031_%E2%98%85_Stiletto_Knife.png",
    "★ Stiletto Knife | Marble Fade": "assets/cases/prisma-case/weapons/032_%E2%98%85_Stiletto_Knife_Marble_Fade.png",
    "★ Stiletto Knife | Tiger Tooth": "assets/cases/prisma-case/weapons/033_%E2%98%85_Stiletto_Knife_Tiger_Tooth.png",
    "★ Stiletto Knife | Doppler": "assets/cases/prisma-case/weapons/040_%E2%98%85_Stiletto_Knife_Doppler.png",
    "★ Stiletto Knife | Damascus Steel": "assets/cases/prisma-case/weapons/041_%E2%98%85_Stiletto_Knife_Damascus_Steel.png",
    "★ Stiletto Knife | Ultraviolet": "assets/cases/prisma-case/weapons/042_%E2%98%85_Stiletto_Knife_Ultraviolet.png",
    "★ Stiletto Knife | Rust Coat": "assets/cases/prisma-case/weapons/043_%E2%98%85_Stiletto_Knife_Rust_Coat.png",
    "★ Talon Knife": "assets/cases/horizon-case/weapons/044_%E2%98%85_Talon_Knife.png",
    "★ Talon Knife | Marble Fade": "assets/cases/prisma-case/weapons/045_%E2%98%85_Talon_Knife_Marble_Fade.png",
    "★ Talon Knife | Tiger Tooth": "assets/cases/prisma-case/weapons/046_%E2%98%85_Talon_Knife_Tiger_Tooth.png",
    "★ Talon Knife | Doppler": "assets/cases/prisma-case/weapons/053_%E2%98%85_Talon_Knife_Doppler.png",
    "★ Talon Knife | Damascus Steel": "assets/cases/prisma-case/weapons/054_%E2%98%85_Talon_Knife_Damascus_Steel.png",
    "★ Talon Knife | Ultraviolet": "assets/cases/prisma-case/weapons/055_%E2%98%85_Talon_Knife_Ultraviolet.png",
    "★ Talon Knife | Rust Coat": "assets/cases/prisma-case/weapons/056_%E2%98%85_Talon_Knife_Rust_Coat.png",
    "★ Ursus Knife": "assets/cases/horizon-case/weapons/057_%E2%98%85_Ursus_Knife.png",
    "★ Ursus Knife | Marble Fade": "assets/cases/prisma-case/weapons/058_%E2%98%85_Ursus_Knife_Marble_Fade.png",
    "★ Ursus Knife | Tiger Tooth": "assets/cases/prisma-case/weapons/059_%E2%98%85_Ursus_Knife_Tiger_Tooth.png",
    "★ Ursus Knife | Doppler": "assets/cases/prisma-case/weapons/066_%E2%98%85_Ursus_Knife_Doppler.png",
    "★ Ursus Knife | Damascus Steel": "assets/cases/prisma-case/weapons/067_%E2%98%85_Ursus_Knife_Damascus_Steel.png",
    "★ Ursus Knife | Ultraviolet": "assets/cases/prisma-case/weapons/068_%E2%98%85_Ursus_Knife_Ultraviolet.png",
    "★ Ursus Knife | Rust Coat": "assets/cases/prisma-case/weapons/069_%E2%98%85_Ursus_Knife_Rust_Coat.png",
    "Dual Berettas | Elite 1.6": "assets/cases/cs20-case/weapons/001_Dual_Berettas_Elite_1.6.png",
    "Tec-9 | Flash Out": "assets/cases/cs20-case/weapons/002_Tec-9_Flash_Out.png",
    "MAC-10 | Classic Crate": "assets/cases/cs20-case/weapons/003_MAC-10_Classic_Crate.png",
    "MAG-7 | Popdog": "assets/cases/cs20-case/weapons/004_MAG-7_Popdog.png",
    "SCAR-20 | Assault": "assets/cases/cs20-case/weapons/005_SCAR-20_Assault.png",
    "FAMAS | Decommissioned": "assets/cases/cs20-case/weapons/006_FAMAS_Decommissioned.png",
    "Glock-18 | Sacrifice": "assets/cases/cs20-case/weapons/007_Glock-18_Sacrifice.png",
    "M249 | Aztec": "assets/cases/cs20-case/weapons/008_M249_Aztec.png",
    "MP5-SD | Agent": "assets/cases/cs20-case/weapons/009_MP5-SD_Agent.png",
    "Five-SeveN | Buddy": "assets/cases/cs20-case/weapons/010_Five-SeveN_Buddy.png",
    "P250 | Inferno": "assets/cases/cs20-case/weapons/011_P250_Inferno.png",
    "UMP-45 | Plastique": "assets/cases/cs20-case/weapons/012_UMP-45_Plastique.png",
    "MP9 | Hydra": "assets/cases/cs20-case/weapons/013_MP9_Hydra.png",
    "P90 | Nostalgia": "assets/cases/cs20-case/weapons/014_P90_Nostalgia.png",
    "AUG | Death by Puppy": "assets/cases/cs20-case/weapons/015_AUG_Death_by_Puppy.png",
    "AWP | Wildfire": "assets/cases/cs20-case/weapons/016_AWP_Wildfire.png",
    "FAMAS | Commemoration": "assets/cases/cs20-case/weapons/017_FAMAS_Commemoration.png",
    "★ Classic Knife": "assets/cases/cs20-case/weapons/018_%E2%98%85_Classic_Knife.png",
    "★ Classic Knife | Fade": "assets/cases/cs20-case/weapons/019_%E2%98%85_Classic_Knife_Fade.png",
    "★ Classic Knife | Crimson Web": "assets/cases/cs20-case/weapons/020_%E2%98%85_Classic_Knife_Crimson_Web.png",
    "★ Classic Knife | Slaughter": "assets/cases/cs20-case/weapons/021_%E2%98%85_Classic_Knife_Slaughter.png",
    "★ Classic Knife | Case Hardened": "assets/cases/cs20-case/weapons/022_%E2%98%85_Classic_Knife_Case_Hardened.png",
    "★ Classic Knife | Urban Masked": "assets/cases/cs20-case/weapons/023_%E2%98%85_Classic_Knife_Urban_Masked.png",
    "★ Classic Knife | Blue Steel": "assets/cases/cs20-case/weapons/024_%E2%98%85_Classic_Knife_Blue_Steel.png",
    "★ Classic Knife | Night Stripe": "assets/cases/cs20-case/weapons/025_%E2%98%85_Classic_Knife_Night_Stripe.png",
    "★ Classic Knife | Stained": "assets/cases/cs20-case/weapons/026_%E2%98%85_Classic_Knife_Stained.png",
    "★ Classic Knife | Forest DDPAT": "assets/cases/cs20-case/weapons/027_%E2%98%85_Classic_Knife_Forest_DDPAT.png",
    "★ Classic Knife | Boreal Forest": "assets/cases/cs20-case/weapons/028_%E2%98%85_Classic_Knife_Boreal_Forest.png",
    "★ Classic Knife | Scorched": "assets/cases/cs20-case/weapons/029_%E2%98%85_Classic_Knife_Scorched.png",
    "★ Classic Knife | Safari Mesh": "assets/cases/cs20-case/weapons/030_%E2%98%85_Classic_Knife_Safari_Mesh.png",
    "FAMAS | Crypsis": "assets/cases/prisma-case/weapons/001_FAMAS_Crypsis.png",
    "AK-47 | Uncharted": "assets/cases/prisma-case/weapons/002_AK-47_Uncharted.png",
    "MAC-10 | Whitefish": "assets/cases/prisma-case/weapons/003_MAC-10_Whitefish.png",
    "Galil AR | Akoben": "assets/cases/prisma-case/weapons/004_Galil_AR_Akoben.png",
    "MP7 | Mischief": "assets/cases/prisma-case/weapons/005_MP7_Mischief.png",
    "P250 | Verdigris": "assets/cases/prisma-case/weapons/006_P250_Verdigris.png",
    "P90 | Off World": "assets/cases/prisma-case/weapons/007_P90_Off_World.png",
    "AWP | Atheris": "assets/cases/prisma-case/weapons/008_AWP_Atheris.png",
    "Tec-9 | Bamboozle": "assets/cases/prisma-case/weapons/009_Tec-9_Bamboozle.png",
    "Desert Eagle | Light Rail": "assets/cases/prisma-case/weapons/010_Desert_Eagle_Light_Rail.png",
    "MP5-SD | Gauss": "assets/cases/prisma-case/weapons/011_MP5-SD_Gauss.png",
    "UMP-45 | Moonrise": "assets/cases/prisma-case/weapons/012_UMP-45_Moonrise.png",
    "R8 Revolver | Skull Crusher": "assets/cases/prisma-case/weapons/013_R8_Revolver_Skull_Crusher.png",
    "AUG | Momentum": "assets/cases/prisma-case/weapons/014_AUG_Momentum.png",
    "XM1014 | Incinegator": "assets/cases/prisma-case/weapons/015_XM1014_Incinegator.png",
    "Five-SeveN | Angry Mob": "assets/cases/prisma-case/weapons/016_Five-SeveN_Angry_Mob.png",
    "M4A4 | The Emperor": "assets/cases/prisma-case/weapons/017_M4A4_The_Emperor.png",
    "MP9 | Modest Threat": "assets/cases/danger-zone-case/weapons/001_MP9_Modest_Threat.png",
    "Glock-18 | Oxide Blaze": "assets/cases/danger-zone-case/weapons/002_Glock-18_Oxide_Blaze.png",
    "Nova | Wood Fired": "assets/cases/danger-zone-case/weapons/003_Nova_Wood_Fired.png",
    "M4A4 | Magnesium": "assets/cases/danger-zone-case/weapons/004_M4A4_Magnesium.png",
    "Sawed-Off | Black Sand": "assets/cases/danger-zone-case/weapons/005_Sawed-Off_Black_Sand.png",
    "SG 553 | Danger Close": "assets/cases/danger-zone-case/weapons/006_SG_553_Danger_Close.png",
    "Tec-9 | Fubar": "assets/cases/danger-zone-case/weapons/007_Tec-9_Fubar.png",
    "G3SG1 | Scavenger": "assets/cases/danger-zone-case/weapons/008_G3SG1_Scavenger.png",
    "Galil AR | Signal": "assets/cases/danger-zone-case/weapons/009_Galil_AR_Signal.png",
    "MAC-10 | Pipe Down": "assets/cases/danger-zone-case/weapons/010_MAC-10_Pipe_Down.png",
    "P250 | Nevermore": "assets/cases/danger-zone-case/weapons/011_P250_Nevermore.png",
    "USP-S | Flashback": "assets/cases/danger-zone-case/weapons/012_USP-S_Flashback.png",
    "UMP-45 | Momentum": "assets/cases/danger-zone-case/weapons/013_UMP-45_Momentum.png",
    "Desert Eagle | Mecha Industries": "assets/cases/danger-zone-case/weapons/014_Desert_Eagle_Mecha_Industries.png",
    "MP5-SD | Phosphor": "assets/cases/danger-zone-case/weapons/015_MP5-SD_Phosphor.png",
    "AK-47 | Asiimov": "assets/cases/danger-zone-case/weapons/016_AK-47_Asiimov.png",
    "AWP | Neo-Noir": "assets/cases/danger-zone-case/weapons/017_AWP_Neo-Noir.png",
    "★ Navaja Knife | Fade": "assets/cases/horizon-case/weapons/019_%E2%98%85_Navaja_Knife_Fade.png",
    "★ Navaja Knife | Crimson Web": "assets/cases/horizon-case/weapons/020_%E2%98%85_Navaja_Knife_Crimson_Web.png",
    "★ Navaja Knife | Slaughter": "assets/cases/horizon-case/weapons/021_%E2%98%85_Navaja_Knife_Slaughter.png",
    "★ Navaja Knife | Case Hardened": "assets/cases/horizon-case/weapons/022_%E2%98%85_Navaja_Knife_Case_Hardened.png",
    "★ Navaja Knife | Urban Masked": "assets/cases/horizon-case/weapons/023_%E2%98%85_Navaja_Knife_Urban_Masked.png",
    "★ Navaja Knife | Blue Steel": "assets/cases/horizon-case/weapons/024_%E2%98%85_Navaja_Knife_Blue_Steel.png",
    "★ Navaja Knife | Night Stripe": "assets/cases/horizon-case/weapons/025_%E2%98%85_Navaja_Knife_Night_Stripe.png",
    "★ Navaja Knife | Stained": "assets/cases/horizon-case/weapons/026_%E2%98%85_Navaja_Knife_Stained.png",
    "★ Navaja Knife | Forest DDPAT": "assets/cases/horizon-case/weapons/027_%E2%98%85_Navaja_Knife_Forest_DDPAT.png",
    "★ Navaja Knife | Boreal Forest": "assets/cases/horizon-case/weapons/028_%E2%98%85_Navaja_Knife_Boreal_Forest.png",
    "★ Navaja Knife | Scorched": "assets/cases/horizon-case/weapons/029_%E2%98%85_Navaja_Knife_Scorched.png",
    "★ Navaja Knife | Safari Mesh": "assets/cases/horizon-case/weapons/030_%E2%98%85_Navaja_Knife_Safari_Mesh.png",
    "★ Stiletto Knife | Fade": "assets/cases/horizon-case/weapons/032_%E2%98%85_Stiletto_Knife_Fade.png",
    "★ Stiletto Knife | Crimson Web": "assets/cases/horizon-case/weapons/033_%E2%98%85_Stiletto_Knife_Crimson_Web.png",
    "★ Stiletto Knife | Slaughter": "assets/cases/horizon-case/weapons/034_%E2%98%85_Stiletto_Knife_Slaughter.png",
    "★ Stiletto Knife | Case Hardened": "assets/cases/horizon-case/weapons/035_%E2%98%85_Stiletto_Knife_Case_Hardened.png",
    "★ Stiletto Knife | Urban Masked": "assets/cases/horizon-case/weapons/036_%E2%98%85_Stiletto_Knife_Urban_Masked.png",
    "★ Stiletto Knife | Blue Steel": "assets/cases/horizon-case/weapons/037_%E2%98%85_Stiletto_Knife_Blue_Steel.png",
    "★ Stiletto Knife | Night Stripe": "assets/cases/horizon-case/weapons/038_%E2%98%85_Stiletto_Knife_Night_Stripe.png",
    "★ Stiletto Knife | Stained": "assets/cases/horizon-case/weapons/039_%E2%98%85_Stiletto_Knife_Stained.png",
    "★ Stiletto Knife | Forest DDPAT": "assets/cases/horizon-case/weapons/040_%E2%98%85_Stiletto_Knife_Forest_DDPAT.png",
    "★ Stiletto Knife | Boreal Forest": "assets/cases/horizon-case/weapons/041_%E2%98%85_Stiletto_Knife_Boreal_Forest.png",
    "★ Stiletto Knife | Scorched": "assets/cases/horizon-case/weapons/042_%E2%98%85_Stiletto_Knife_Scorched.png",
    "★ Stiletto Knife | Safari Mesh": "assets/cases/horizon-case/weapons/043_%E2%98%85_Stiletto_Knife_Safari_Mesh.png",
    "★ Talon Knife | Fade": "assets/cases/horizon-case/weapons/045_%E2%98%85_Talon_Knife_Fade.png",
    "★ Talon Knife | Crimson Web": "assets/cases/horizon-case/weapons/046_%E2%98%85_Talon_Knife_Crimson_Web.png",
    "★ Talon Knife | Slaughter": "assets/cases/horizon-case/weapons/047_%E2%98%85_Talon_Knife_Slaughter.png",
    "★ Talon Knife | Case Hardened": "assets/cases/horizon-case/weapons/048_%E2%98%85_Talon_Knife_Case_Hardened.png",
    "★ Talon Knife | Urban Masked": "assets/cases/horizon-case/weapons/049_%E2%98%85_Talon_Knife_Urban_Masked.png",
    "★ Talon Knife | Blue Steel": "assets/cases/horizon-case/weapons/050_%E2%98%85_Talon_Knife_Blue_Steel.png",
    "★ Talon Knife | Night Stripe": "assets/cases/horizon-case/weapons/051_%E2%98%85_Talon_Knife_Night_Stripe.png",
    "★ Talon Knife | Stained": "assets/cases/horizon-case/weapons/052_%E2%98%85_Talon_Knife_Stained.png",
    "★ Talon Knife | Forest DDPAT": "assets/cases/horizon-case/weapons/053_%E2%98%85_Talon_Knife_Forest_DDPAT.png",
    "★ Talon Knife | Boreal Forest": "assets/cases/horizon-case/weapons/054_%E2%98%85_Talon_Knife_Boreal_Forest.png",
    "★ Talon Knife | Scorched": "assets/cases/horizon-case/weapons/055_%E2%98%85_Talon_Knife_Scorched.png",
    "★ Talon Knife | Safari Mesh": "assets/cases/horizon-case/weapons/056_%E2%98%85_Talon_Knife_Safari_Mesh.png",
    "★ Ursus Knife | Fade": "assets/cases/horizon-case/weapons/058_%E2%98%85_Ursus_Knife_Fade.png",
    "★ Ursus Knife | Crimson Web": "assets/cases/horizon-case/weapons/059_%E2%98%85_Ursus_Knife_Crimson_Web.png",
    "★ Ursus Knife | Slaughter": "assets/cases/horizon-case/weapons/060_%E2%98%85_Ursus_Knife_Slaughter.png",
    "★ Ursus Knife | Case Hardened": "assets/cases/horizon-case/weapons/061_%E2%98%85_Ursus_Knife_Case_Hardened.png",
    "★ Ursus Knife | Urban Masked": "assets/cases/horizon-case/weapons/062_%E2%98%85_Ursus_Knife_Urban_Masked.png",
    "★ Ursus Knife | Blue Steel": "assets/cases/horizon-case/weapons/063_%E2%98%85_Ursus_Knife_Blue_Steel.png",
    "★ Ursus Knife | Night Stripe": "assets/cases/horizon-case/weapons/064_%E2%98%85_Ursus_Knife_Night_Stripe.png",
    "★ Ursus Knife | Stained": "assets/cases/horizon-case/weapons/065_%E2%98%85_Ursus_Knife_Stained.png",
    "★ Ursus Knife | Forest DDPAT": "assets/cases/horizon-case/weapons/066_%E2%98%85_Ursus_Knife_Forest_DDPAT.png",
    "★ Ursus Knife | Boreal Forest": "assets/cases/horizon-case/weapons/067_%E2%98%85_Ursus_Knife_Boreal_Forest.png",
    "★ Ursus Knife | Scorched": "assets/cases/horizon-case/weapons/068_%E2%98%85_Ursus_Knife_Scorched.png",
    "★ Ursus Knife | Safari Mesh": "assets/cases/horizon-case/weapons/069_%E2%98%85_Ursus_Knife_Safari_Mesh.png",
    "AUG | Amber Slipstream": "assets/cases/horizon-case/weapons/001_AUG_Amber_Slipstream.png",
    "Dual Berettas | Shred": "assets/cases/horizon-case/weapons/002_Dual_Berettas_Shred.png",
    "Glock-18 | Warhawk": "assets/cases/horizon-case/weapons/003_Glock-18_Warhawk.png",
    "MP9 | Capillary": "assets/cases/horizon-case/weapons/004_MP9_Capillary.png",
    "P90 | Traction": "assets/cases/horizon-case/weapons/005_P90_Traction.png",
    "R8 Revolver | Survivalist": "assets/cases/horizon-case/weapons/006_R8_Revolver_Survivalist.png",
    "Tec-9 | Snek-9": "assets/cases/horizon-case/weapons/007_Tec-9_Snek-9.png",
    "CZ75-Auto | Eco": "assets/cases/horizon-case/weapons/008_CZ75-Auto_Eco.png",
    "G3SG1 | High Seas": "assets/cases/horizon-case/weapons/009_G3SG1_High_Seas.png",
    "Nova | Toy Soldier": "assets/cases/horizon-case/weapons/010_Nova_Toy_Soldier.png",
    "AWP | PAW": "assets/cases/horizon-case/weapons/011_AWP_PAW.png",
    "MP7 | Powercore": "assets/cases/horizon-case/weapons/012_MP7_Powercore.png",
    "M4A1-S | Nightmare": "assets/cases/horizon-case/weapons/013_M4A1-S_Nightmare.png",
    "Sawed-Off | Devourer": "assets/cases/horizon-case/weapons/014_Sawed-Off_Devourer.png",
    "FAMAS | Eye of Athena": "assets/cases/horizon-case/weapons/015_FAMAS_Eye_of_Athena.png",
    "AK-47 | Neon Rider": "assets/cases/horizon-case/weapons/016_AK-47_Neon_Rider.png",
    "Desert Eagle | Code Red": "assets/cases/horizon-case/weapons/017_Desert_Eagle_Code_Red.png",
    "PP-Bizon | Night Riot": "assets/cases/clutch-case/weapons/001_PP-Bizon_Night_Riot.png",
    "Five-SeveN | Flame Test": "assets/cases/clutch-case/weapons/002_Five-SeveN_Flame_Test.png",
    "MP9 | Black Sand": "assets/cases/clutch-case/weapons/003_MP9_Black_Sand.png",
    "P2000 | Urban Hazard": "assets/cases/clutch-case/weapons/004_P2000_Urban_Hazard.png",
    "R8 Revolver | Grip": "assets/cases/clutch-case/weapons/005_R8_Revolver_Grip.png",
    "SG 553 | Aloha": "assets/cases/clutch-case/weapons/006_SG_553_Aloha.png",
    "XM1014 | Oxide Blaze": "assets/cases/clutch-case/weapons/007_XM1014_Oxide_Blaze.png",
    "Glock-18 | Moonrise": "assets/cases/clutch-case/weapons/008_Glock-18_Moonrise.png",
    "Negev | Lionfish": "assets/cases/clutch-case/weapons/009_Negev_Lionfish.png",
    "Nova | Wild Six": "assets/cases/clutch-case/weapons/010_Nova_Wild_Six.png",
    "MAG-7 | SWAG-7": "assets/cases/clutch-case/weapons/011_MAG-7_SWAG-7.png",
    "UMP-45 | Arctic Wolf": "assets/cases/clutch-case/weapons/012_UMP-45_Arctic_Wolf.png",
    "AUG | Stymphalian": "assets/cases/clutch-case/weapons/013_AUG_Stymphalian.png",
    "AWP | Mortis": "assets/cases/clutch-case/weapons/014_AWP_Mortis.png",
    "USP-S | Cortex": "assets/cases/clutch-case/weapons/015_USP-S_Cortex.png",
    "M4A4 | Neo-Noir": "assets/cases/clutch-case/weapons/016_M4A4_Neo-Noir.png",
    "MP7 | Bloodsport": "assets/cases/clutch-case/weapons/017_MP7_Bloodsport.png",
    "Sawed-Off | Morris": "assets/cases/spectrum-2-case/weapons/001_Sawed-Off_Morris.png",
    "AUG | Triqua": "assets/cases/spectrum-2-case/weapons/002_AUG_Triqua.png",
    "G3SG1 | Hunter": "assets/cases/spectrum-2-case/weapons/003_G3SG1_Hunter.png",
    "Glock-18 | Off World": "assets/cases/spectrum-2-case/weapons/004_Glock-18_Off_World.png",
    "MAC-10 | Oceanic": "assets/cases/spectrum-2-case/weapons/005_MAC-10_Oceanic.png",
    "Tec-9 | Cracked Opal": "assets/cases/spectrum-2-case/weapons/006_Tec-9_Cracked_Opal.png",
    "SCAR-20 | Jungle Slipstream": "assets/cases/spectrum-2-case/weapons/007_SCAR-20_Jungle_Slipstream.png",
    "MP9 | Goo": "assets/cases/spectrum-2-case/weapons/008_MP9_Goo.png",
    "SG 553 | Phantom": "assets/cases/spectrum-2-case/weapons/009_SG_553_Phantom.png",
    "CZ75-Auto | Tacticat": "assets/cases/spectrum-2-case/weapons/010_CZ75-Auto_Tacticat.png",
    "UMP-45 | Exposure": "assets/cases/spectrum-2-case/weapons/011_UMP-45_Exposure.png",
    "XM1014 | Ziggy": "assets/cases/spectrum-2-case/weapons/012_XM1014_Ziggy.png",
    "PP-Bizon | High Roller": "assets/cases/spectrum-2-case/weapons/013_PP-Bizon_High_Roller.png",
    "M4A1-S | Leaded Glass": "assets/cases/spectrum-2-case/weapons/014_M4A1-S_Leaded_Glass.png",
    "R8 Revolver | Llama Cannon": "assets/cases/spectrum-2-case/weapons/015_R8_Revolver_Llama_Cannon.png",
    "AK-47 | The Empress": "assets/cases/spectrum-2-case/weapons/016_AK-47_The_Empress.png",
    "P250 | See Ya Later": "assets/cases/spectrum-2-case/weapons/017_P250_See_Ya_Later.png",
    "★ Bowie Knife | Marble Fade": "assets/cases/spectrum-case/weapons/018_%E2%98%85_Bowie_Knife_Marble_Fade.png",
    "★ Bowie Knife | Tiger Tooth": "assets/cases/spectrum-case/weapons/019_%E2%98%85_Bowie_Knife_Tiger_Tooth.png",
    "★ Bowie Knife | Doppler": "assets/cases/spectrum-case/weapons/026_%E2%98%85_Bowie_Knife_Doppler.png",
    "★ Bowie Knife | Damascus Steel": "assets/cases/spectrum-case/weapons/027_%E2%98%85_Bowie_Knife_Damascus_Steel.png",
    "★ Bowie Knife | Ultraviolet": "assets/cases/spectrum-case/weapons/028_%E2%98%85_Bowie_Knife_Ultraviolet.png",
    "★ Bowie Knife | Rust Coat": "assets/cases/spectrum-case/weapons/029_%E2%98%85_Bowie_Knife_Rust_Coat.png",
    "★ Butterfly Knife | Marble Fade": "assets/cases/spectrum-case/weapons/030_%E2%98%85_Butterfly_Knife_Marble_Fade.png",
    "★ Butterfly Knife | Tiger Tooth": "assets/cases/spectrum-case/weapons/031_%E2%98%85_Butterfly_Knife_Tiger_Tooth.png",
    "★ Butterfly Knife | Doppler": "assets/cases/spectrum-case/weapons/038_%E2%98%85_Butterfly_Knife_Doppler.png",
    "★ Butterfly Knife | Damascus Steel": "assets/cases/spectrum-case/weapons/039_%E2%98%85_Butterfly_Knife_Damascus_Steel.png",
    "★ Butterfly Knife | Ultraviolet": "assets/cases/spectrum-case/weapons/040_%E2%98%85_Butterfly_Knife_Ultraviolet.png",
    "★ Butterfly Knife | Rust Coat": "assets/cases/spectrum-case/weapons/041_%E2%98%85_Butterfly_Knife_Rust_Coat.png",
    "★ Falchion Knife | Marble Fade": "assets/cases/spectrum-case/weapons/042_%E2%98%85_Falchion_Knife_Marble_Fade.png",
    "★ Falchion Knife | Tiger Tooth": "assets/cases/spectrum-case/weapons/043_%E2%98%85_Falchion_Knife_Tiger_Tooth.png",
    "★ Falchion Knife | Doppler": "assets/cases/spectrum-case/weapons/050_%E2%98%85_Falchion_Knife_Doppler.png",
    "★ Falchion Knife | Damascus Steel": "assets/cases/spectrum-case/weapons/051_%E2%98%85_Falchion_Knife_Damascus_Steel.png",
    "★ Falchion Knife | Ultraviolet": "assets/cases/spectrum-case/weapons/052_%E2%98%85_Falchion_Knife_Ultraviolet.png",
    "★ Falchion Knife | Rust Coat": "assets/cases/spectrum-case/weapons/053_%E2%98%85_Falchion_Knife_Rust_Coat.png",
    "★ Huntsman Knife | Marble Fade": "assets/cases/spectrum-case/weapons/054_%E2%98%85_Huntsman_Knife_Marble_Fade.png",
    "★ Huntsman Knife | Tiger Tooth": "assets/cases/spectrum-case/weapons/055_%E2%98%85_Huntsman_Knife_Tiger_Tooth.png",
    "★ Huntsman Knife | Doppler": "assets/cases/spectrum-case/weapons/062_%E2%98%85_Huntsman_Knife_Doppler.png",
    "★ Huntsman Knife | Damascus Steel": "assets/cases/spectrum-case/weapons/063_%E2%98%85_Huntsman_Knife_Damascus_Steel.png",
    "★ Huntsman Knife | Ultraviolet": "assets/cases/spectrum-case/weapons/064_%E2%98%85_Huntsman_Knife_Ultraviolet.png",
    "★ Huntsman Knife | Rust Coat": "assets/cases/spectrum-case/weapons/065_%E2%98%85_Huntsman_Knife_Rust_Coat.png",
    "★ Shadow Daggers | Marble Fade": "assets/cases/spectrum-case/weapons/066_%E2%98%85_Shadow_Daggers_Marble_Fade.png",
    "★ Shadow Daggers | Tiger Tooth": "assets/cases/spectrum-case/weapons/067_%E2%98%85_Shadow_Daggers_Tiger_Tooth.png",
    "★ Shadow Daggers | Doppler": "assets/cases/spectrum-case/weapons/074_%E2%98%85_Shadow_Daggers_Doppler.png",
    "★ Shadow Daggers | Damascus Steel": "assets/cases/spectrum-case/weapons/075_%E2%98%85_Shadow_Daggers_Damascus_Steel.png",
    "★ Shadow Daggers | Ultraviolet": "assets/cases/spectrum-case/weapons/076_%E2%98%85_Shadow_Daggers_Ultraviolet.png",
    "★ Shadow Daggers | Rust Coat": "assets/cases/spectrum-case/weapons/077_%E2%98%85_Shadow_Daggers_Rust_Coat.png",
    "PP-Bizon | Jungle Slipstream": "assets/cases/spectrum-case/weapons/001_PP-Bizon_Jungle_Slipstream.png",
    "SCAR-20 | Blueprint": "assets/cases/spectrum-case/weapons/002_SCAR-20_Blueprint.png",
    "Desert Eagle | Oxide Blaze": "assets/cases/spectrum-case/weapons/003_Desert_Eagle_Oxide_Blaze.png",
    "Five-SeveN | Capillary": "assets/cases/spectrum-case/weapons/004_Five-SeveN_Capillary.png",
    "MP7 | Akoben": "assets/cases/spectrum-case/weapons/005_MP7_Akoben.png",
    "P250 | Ripple": "assets/cases/spectrum-case/weapons/006_P250_Ripple.png",
    "Sawed-Off | Zander": "assets/cases/spectrum-case/weapons/007_Sawed-Off_Zander.png",
    "Galil AR | Crimson Tsunami": "assets/cases/spectrum-case/weapons/008_Galil_AR_Crimson_Tsunami.png",
    "M249 | Emerald Poison Dart": "assets/cases/spectrum-case/weapons/009_M249_Emerald_Poison_Dart.png",
    "MAC-10 | Last Dive": "assets/cases/spectrum-case/weapons/010_MAC-10_Last_Dive.png",
    "UMP-45 | Scaffold": "assets/cases/spectrum-case/weapons/011_UMP-45_Scaffold.png",
    "XM1014 | Seasons": "assets/cases/spectrum-case/weapons/012_XM1014_Seasons.png",
    "AWP | Fever Dream": "assets/cases/spectrum-case/weapons/013_AWP_Fever_Dream.png",
    "CZ75-Auto | Xiangliu": "assets/cases/spectrum-case/weapons/014_CZ75-Auto_Xiangliu.png",
    "M4A1-S | Decimator": "assets/cases/spectrum-case/weapons/015_M4A1-S_Decimator.png",
    "AK-47 | Bloodsport": "assets/cases/spectrum-case/weapons/016_AK-47_Bloodsport.png",
    "USP-S | Neo-Noir": "assets/cases/spectrum-case/weapons/017_USP-S_Neo-Noir.png",
    "CZ75-Auto | Imprint": "assets/cases/gamma-2-case/weapons/001_CZ75-Auto_Imprint.png",
    "Five-SeveN | Scumbria": "assets/cases/gamma-2-case/weapons/002_Five-SeveN_Scumbria.png",
    "G3SG1 | Ventilator": "assets/cases/gamma-2-case/weapons/003_G3SG1_Ventilator.png",
    "Negev | Dazzle": "assets/cases/gamma-2-case/weapons/004_Negev_Dazzle.png",
    "P90 | Grim": "assets/cases/gamma-2-case/weapons/005_P90_Grim.png",
    "UMP-45 | Briefing": "assets/cases/gamma-2-case/weapons/006_UMP-45_Briefing.png",
    "XM1014 | Slipstream": "assets/cases/gamma-2-case/weapons/007_XM1014_Slipstream.png",
    "Desert Eagle | Directive": "assets/cases/gamma-2-case/weapons/008_Desert_Eagle_Directive.png",
    "Glock-18 | Weasel": "assets/cases/gamma-2-case/weapons/009_Glock-18_Weasel.png",
    "MAG-7 | Petroglyph": "assets/cases/gamma-2-case/weapons/010_MAG-7_Petroglyph.png",
    "SCAR-20 | Powercore": "assets/cases/gamma-2-case/weapons/011_SCAR-20_Powercore.png",
    "SG 553 | Triarch": "assets/cases/gamma-2-case/weapons/012_SG_553_Triarch.png",
    "AUG | Syd Mead": "assets/cases/gamma-2-case/weapons/013_AUG_Syd_Mead.png",
    "MP9 | Airlock": "assets/cases/gamma-2-case/weapons/014_MP9_Airlock.png",
    "Tec-9 | Fuel Injector": "assets/cases/gamma-2-case/weapons/015_Tec-9_Fuel_Injector.png",
    "AK-47 | Neon Revolution": "assets/cases/gamma-2-case/weapons/016_AK-47_Neon_Revolution.png",
    "FAMAS | Roll Cage": "assets/cases/gamma-2-case/weapons/017_FAMAS_Roll_Cage.png",
    "★ Bayonet | Gamma Doppler": "assets/cases/gamma-case/weapons/022_%E2%98%85_Bayonet_Gamma_Doppler.png",
    "★ Bayonet | Lore": "assets/cases/gamma-case/weapons/023_%E2%98%85_Bayonet_Lore.png",
    "★ Bayonet | Autotronic": "assets/cases/gamma-case/weapons/024_%E2%98%85_Bayonet_Autotronic.png",
    "★ Bayonet | Black Laminate": "assets/cases/gamma-case/weapons/025_%E2%98%85_Bayonet_Black_Laminate.png",
    "★ Bayonet | Freehand": "assets/cases/gamma-case/weapons/026_%E2%98%85_Bayonet_Freehand.png",
    "★ Bayonet | Bright Water": "assets/cases/gamma-case/weapons/027_%E2%98%85_Bayonet_Bright_Water.png",
    "★ Flip Knife | Gamma Doppler": "assets/cases/gamma-case/weapons/032_%E2%98%85_Flip_Knife_Gamma_Doppler.png",
    "★ Flip Knife | Lore": "assets/cases/gamma-case/weapons/033_%E2%98%85_Flip_Knife_Lore.png",
    "★ Flip Knife | Autotronic": "assets/cases/gamma-case/weapons/034_%E2%98%85_Flip_Knife_Autotronic.png",
    "★ Flip Knife | Black Laminate": "assets/cases/gamma-case/weapons/035_%E2%98%85_Flip_Knife_Black_Laminate.png",
    "★ Flip Knife | Freehand": "assets/cases/gamma-case/weapons/036_%E2%98%85_Flip_Knife_Freehand.png",
    "★ Flip Knife | Bright Water": "assets/cases/gamma-case/weapons/037_%E2%98%85_Flip_Knife_Bright_Water.png",
    "★ Gut Knife | Gamma Doppler": "assets/cases/gamma-case/weapons/042_%E2%98%85_Gut_Knife_Gamma_Doppler.png",
    "★ Gut Knife | Lore": "assets/cases/gamma-case/weapons/043_%E2%98%85_Gut_Knife_Lore.png",
    "★ Gut Knife | Autotronic": "assets/cases/gamma-case/weapons/044_%E2%98%85_Gut_Knife_Autotronic.png",
    "★ Gut Knife | Black Laminate": "assets/cases/gamma-case/weapons/045_%E2%98%85_Gut_Knife_Black_Laminate.png",
    "★ Gut Knife | Bright Water": "assets/cases/gamma-case/weapons/046_%E2%98%85_Gut_Knife_Bright_Water.png",
    "★ Gut Knife | Freehand": "assets/cases/gamma-case/weapons/047_%E2%98%85_Gut_Knife_Freehand.png",
    "★ Karambit | Gamma Doppler": "assets/cases/gamma-case/weapons/052_%E2%98%85_Karambit_Gamma_Doppler.png",
    "★ Karambit | Lore": "assets/cases/gamma-case/weapons/053_%E2%98%85_Karambit_Lore.png",
    "★ Karambit | Autotronic": "assets/cases/gamma-case/weapons/054_%E2%98%85_Karambit_Autotronic.png",
    "★ Karambit | Black Laminate": "assets/cases/gamma-case/weapons/055_%E2%98%85_Karambit_Black_Laminate.png",
    "★ Karambit | Freehand": "assets/cases/gamma-case/weapons/056_%E2%98%85_Karambit_Freehand.png",
    "★ Karambit | Bright Water": "assets/cases/gamma-case/weapons/057_%E2%98%85_Karambit_Bright_Water.png",
    "★ M9 Bayonet | Gamma Doppler": "assets/cases/gamma-case/weapons/062_%E2%98%85_M9_Bayonet_Gamma_Doppler.png",
    "★ M9 Bayonet | Lore": "assets/cases/gamma-case/weapons/063_%E2%98%85_M9_Bayonet_Lore.png",
    "★ M9 Bayonet | Autotronic": "assets/cases/gamma-case/weapons/064_%E2%98%85_M9_Bayonet_Autotronic.png",
    "★ M9 Bayonet | Black Laminate": "assets/cases/gamma-case/weapons/065_%E2%98%85_M9_Bayonet_Black_Laminate.png",
    "★ M9 Bayonet | Bright Water": "assets/cases/gamma-case/weapons/066_%E2%98%85_M9_Bayonet_Bright_Water.png",
    "★ M9 Bayonet | Freehand": "assets/cases/gamma-case/weapons/067_%E2%98%85_M9_Bayonet_Freehand.png",
    "Five-SeveN | Violent Daimyo": "assets/cases/gamma-case/weapons/001_Five-SeveN_Violent_Daimyo.png",
    "MAC-10 | Carnivore": "assets/cases/gamma-case/weapons/002_MAC-10_Carnivore.png",
    "Nova | Exo": "assets/cases/gamma-case/weapons/003_Nova_Exo.png",
    "P250 | Iron Clad": "assets/cases/gamma-case/weapons/004_P250_Iron_Clad.png",
    "PP-Bizon | Harvester": "assets/cases/gamma-case/weapons/005_PP-Bizon_Harvester.png",
    "SG 553 | Aerial": "assets/cases/gamma-case/weapons/006_SG_553_Aerial.png",
    "Tec-9 | Ice Cap": "assets/cases/gamma-case/weapons/007_Tec-9_Ice_Cap.png",
    "AUG | Aristocrat": "assets/cases/gamma-case/weapons/008_AUG_Aristocrat.png",
    "AWP | Phobos": "assets/cases/gamma-case/weapons/009_AWP_Phobos.png",
    "P90 | Chopper": "assets/cases/gamma-case/weapons/010_P90_Chopper.png",
    "R8 Revolver | Reboot": "assets/cases/gamma-case/weapons/011_R8_Revolver_Reboot.png",
    "Sawed-Off | Limelight": "assets/cases/gamma-case/weapons/012_Sawed-Off_Limelight.png",
    "M4A4 | Desolate Space": "assets/cases/gamma-case/weapons/013_M4A4_Desolate_Space.png",
    "P2000 | Imperial Dragon": "assets/cases/gamma-case/weapons/014_P2000_Imperial_Dragon.png",
    "SCAR-20 | Bloodsport": "assets/cases/gamma-case/weapons/015_SCAR-20_Bloodsport.png",
    "Glock-18 | Wasteland Rebel": "assets/cases/gamma-case/weapons/016_Glock-18_Wasteland_Rebel.png",
    "M4A1-S | Mecha Industries": "assets/cases/gamma-case/weapons/017_M4A1-S_Mecha_Industries.png",
    "Dual Berettas | Ventilators": "assets/cases/chroma-3-case/weapons/001_Dual_Berettas_Ventilators.png",
    "G3SG1 | Orange Crash": "assets/cases/chroma-3-case/weapons/002_G3SG1_Orange_Crash.png",
    "M249 | Spectre": "assets/cases/chroma-3-case/weapons/003_M249_Spectre.png",
    "MP9 | Bioleak": "assets/cases/chroma-3-case/weapons/004_MP9_Bioleak.png",
    "P2000 | Oceanic": "assets/cases/chroma-3-case/weapons/005_P2000_Oceanic.png",
    "Sawed-Off | Fubar": "assets/cases/chroma-3-case/weapons/006_Sawed-Off_Fubar.png",
    "SG 553 | Atlas": "assets/cases/chroma-3-case/weapons/007_SG_553_Atlas.png",
    "CZ75-Auto | Red Astor": "assets/cases/chroma-3-case/weapons/008_CZ75-Auto_Red_Astor.png",
    "Galil AR | Firefight": "assets/cases/chroma-3-case/weapons/009_Galil_AR_Firefight.png",
    "SSG 08 | Ghost Crusader": "assets/cases/chroma-3-case/weapons/010_SSG_08_Ghost_Crusader.png",
    "Tec-9 | Re-Entry": "assets/cases/chroma-3-case/weapons/011_Tec-9_Re-Entry.png",
    "XM1014 | Black Tie": "assets/cases/chroma-3-case/weapons/012_XM1014_Black_Tie.png",
    "AUG | Fleet Flock": "assets/cases/chroma-3-case/weapons/013_AUG_Fleet_Flock.png",
    "P250 | Asiimov": "assets/cases/chroma-3-case/weapons/014_P250_Asiimov.png",
    "UMP-45 | Primal Saber": "assets/cases/chroma-3-case/weapons/015_UMP-45_Primal_Saber.png",
    "PP-Bizon | Judgement of Anubis": "assets/cases/chroma-3-case/weapons/016_PP-Bizon_Judgement_of_Anubis.png",
    "M4A1-S | Chantico's Fire": "assets/cases/chroma-3-case/weapons/017_M4A1-S_Chantico's_Fire.png",
    "★ Bayonet | Marble Fade": "assets/cases/chroma-case/weapons/015_%E2%98%85_Bayonet_Marble_Fade.png",
    "★ Bayonet | Tiger Tooth": "assets/cases/chroma-case/weapons/016_%E2%98%85_Bayonet_Tiger_Tooth.png",
    "★ Bayonet | Doppler": "assets/cases/chroma-case/weapons/023_%E2%98%85_Bayonet_Doppler.png",
    "★ Bayonet | Damascus Steel": "assets/cases/chroma-case/weapons/024_%E2%98%85_Bayonet_Damascus_Steel.png",
    "★ Bayonet | Ultraviolet": "assets/cases/chroma-case/weapons/025_%E2%98%85_Bayonet_Ultraviolet.png",
    "★ Bayonet | Rust Coat": "assets/cases/chroma-case/weapons/026_%E2%98%85_Bayonet_Rust_Coat.png",
    "★ Flip Knife | Marble Fade": "assets/cases/chroma-case/weapons/027_%E2%98%85_Flip_Knife_Marble_Fade.png",
    "★ Flip Knife | Tiger Tooth": "assets/cases/chroma-case/weapons/028_%E2%98%85_Flip_Knife_Tiger_Tooth.png",
    "★ Flip Knife | Doppler": "assets/cases/chroma-case/weapons/035_%E2%98%85_Flip_Knife_Doppler.png",
    "★ Flip Knife | Damascus Steel": "assets/cases/chroma-case/weapons/036_%E2%98%85_Flip_Knife_Damascus_Steel.png",
    "★ Flip Knife | Ultraviolet": "assets/cases/chroma-case/weapons/037_%E2%98%85_Flip_Knife_Ultraviolet.png",
    "★ Flip Knife | Rust Coat": "assets/cases/chroma-case/weapons/038_%E2%98%85_Flip_Knife_Rust_Coat.png",
    "★ Gut Knife | Marble Fade": "assets/cases/chroma-case/weapons/039_%E2%98%85_Gut_Knife_Marble_Fade.png",
    "★ Gut Knife | Tiger Tooth": "assets/cases/chroma-case/weapons/040_%E2%98%85_Gut_Knife_Tiger_Tooth.png",
    "★ Gut Knife | Doppler": "assets/cases/chroma-case/weapons/047_%E2%98%85_Gut_Knife_Doppler.png",
    "★ Gut Knife | Damascus Steel": "assets/cases/chroma-case/weapons/048_%E2%98%85_Gut_Knife_Damascus_Steel.png",
    "★ Gut Knife | Ultraviolet": "assets/cases/chroma-case/weapons/049_%E2%98%85_Gut_Knife_Ultraviolet.png",
    "★ Gut Knife | Rust Coat": "assets/cases/chroma-case/weapons/050_%E2%98%85_Gut_Knife_Rust_Coat.png",
    "★ Karambit | Marble Fade": "assets/cases/chroma-case/weapons/051_%E2%98%85_Karambit_Marble_Fade.png",
    "★ Karambit | Tiger Tooth": "assets/cases/chroma-case/weapons/052_%E2%98%85_Karambit_Tiger_Tooth.png",
    "★ Karambit | Doppler": "assets/cases/chroma-case/weapons/059_%E2%98%85_Karambit_Doppler.png",
    "★ Karambit | Damascus Steel": "assets/cases/chroma-case/weapons/060_%E2%98%85_Karambit_Damascus_Steel.png",
    "★ Karambit | Ultraviolet": "assets/cases/chroma-case/weapons/061_%E2%98%85_Karambit_Ultraviolet.png",
    "★ Karambit | Rust Coat": "assets/cases/chroma-case/weapons/062_%E2%98%85_Karambit_Rust_Coat.png",
    "★ M9 Bayonet | Marble Fade": "assets/cases/chroma-case/weapons/063_%E2%98%85_M9_Bayonet_Marble_Fade.png",
    "★ M9 Bayonet | Tiger Tooth": "assets/cases/chroma-case/weapons/064_%E2%98%85_M9_Bayonet_Tiger_Tooth.png",
    "★ M9 Bayonet | Doppler": "assets/cases/chroma-case/weapons/071_%E2%98%85_M9_Bayonet_Doppler.png",
    "★ M9 Bayonet | Damascus Steel": "assets/cases/chroma-case/weapons/072_%E2%98%85_M9_Bayonet_Damascus_Steel.png",
    "★ M9 Bayonet | Ultraviolet": "assets/cases/chroma-case/weapons/073_%E2%98%85_M9_Bayonet_Ultraviolet.png",
    "★ M9 Bayonet | Rust Coat": "assets/cases/chroma-case/weapons/074_%E2%98%85_M9_Bayonet_Rust_Coat.png",
    "AK-47 | Elite Build": "assets/cases/chroma-2-case/weapons/001_AK-47_Elite_Build.png",
    "MP7 | Armor Core": "assets/cases/chroma-2-case/weapons/002_MP7_Armor_Core.png",
    "Desert Eagle | Bronze Deco": "assets/cases/chroma-2-case/weapons/003_Desert_Eagle_Bronze_Deco.png",
    "P250 | Valence": "assets/cases/chroma-2-case/weapons/004_P250_Valence.png",
    "Negev | Man-o'-war": "assets/cases/chroma-2-case/weapons/005_Negev_Man-o'-war.png",
    "Sawed-Off | Origami": "assets/cases/chroma-2-case/weapons/006_Sawed-Off_Origami.png",
    "AWP | Worm God": "assets/cases/chroma-2-case/weapons/007_AWP_Worm_God.png",
    "MAG-7 | Heat": "assets/cases/chroma-2-case/weapons/008_MAG-7_Heat.png",
    "CZ75-Auto | Pole Position": "assets/cases/chroma-2-case/weapons/009_CZ75-Auto_Pole_Position.png",
    "UMP-45 | Grand Prix": "assets/cases/chroma-2-case/weapons/010_UMP-45_Grand_Prix.png",
    "Five-SeveN | Monkey Business": "assets/cases/chroma-2-case/weapons/011_Five-SeveN_Monkey_Business.png",
    "Galil AR | Eco": "assets/cases/chroma-2-case/weapons/012_Galil_AR_Eco.png",
    "FAMAS | Djinn": "assets/cases/chroma-2-case/weapons/013_FAMAS_Djinn.png",
    "M4A1-S | Hyper Beast": "assets/cases/chroma-2-case/weapons/014_M4A1-S_Hyper_Beast.png",
    "MAC-10 | Neon Rider": "assets/cases/chroma-2-case/weapons/015_MAC-10_Neon_Rider.png",
    "Glock-18 | Catacombs": "assets/cases/chroma-case/weapons/001_Glock-18_Catacombs.png",
    "M249 | System Lock": "assets/cases/chroma-case/weapons/002_M249_System_Lock.png",
    "MP9 | Deadly Poison": "assets/cases/chroma-case/weapons/003_MP9_Deadly_Poison.png",
    "SCAR-20 | Grotto": "assets/cases/chroma-case/weapons/004_SCAR-20_Grotto.png",
    "XM1014 | Quicksilver": "assets/cases/chroma-case/weapons/005_XM1014_Quicksilver.png",
    "Dual Berettas | Urban Shock": "assets/cases/chroma-case/weapons/006_Dual_Berettas_Urban_Shock.png",
    "Desert Eagle | Naga": "assets/cases/chroma-case/weapons/007_Desert_Eagle_Naga.png",
    "MAC-10 | Malachite": "assets/cases/chroma-case/weapons/008_MAC-10_Malachite.png",
    "Sawed-Off | Serenity": "assets/cases/chroma-case/weapons/009_Sawed-Off_Serenity.png",
    "AK-47 | Cartel": "assets/cases/chroma-case/weapons/010_AK-47_Cartel.png",
    "M4A4 | 龍王 (Dragon King)": "assets/cases/chroma-case/weapons/011_M4A4_%E9%BE%8D%E7%8E%8B_(Dragon_King).png",
    "P250 | Muertos": "assets/cases/chroma-case/weapons/012_P250_Muertos.png",
    "AWP | Man-o'-war": "assets/cases/chroma-case/weapons/013_AWP_Man-o'-war.png",
    "Galil AR | Chatterbox": "assets/cases/chroma-case/weapons/014_Galil_AR_Chatterbox.png",
    "Galil AR | Rocket Pop": "assets/cases/falchion-case/weapons/001_Galil_AR_Rocket_Pop.png",
    "Glock-18 | Bunsen Burner": "assets/cases/falchion-case/weapons/002_Glock-18_Bunsen_Burner.png",
    "Nova | Ranger": "assets/cases/falchion-case/weapons/003_Nova_Ranger.png",
    "P90 | Elite Build": "assets/cases/falchion-case/weapons/004_P90_Elite_Build.png",
    "UMP-45 | Riot": "assets/cases/falchion-case/weapons/005_UMP-45_Riot.png",
    "USP-S | Torque": "assets/cases/falchion-case/weapons/006_USP-S_Torque.png",
    "FAMAS | Neural Net": "assets/cases/falchion-case/weapons/007_FAMAS_Neural_Net.png",
    "M4A4 | Evil Daimyo": "assets/cases/falchion-case/weapons/008_M4A4_Evil_Daimyo.png",
    "MP9 | Ruby Poison Dart": "assets/cases/falchion-case/weapons/009_MP9_Ruby_Poison_Dart.png",
    "Negev | Loudmouth": "assets/cases/falchion-case/weapons/010_Negev_Loudmouth.png",
    "P2000 | Handgun": "assets/cases/falchion-case/weapons/011_P2000_Handgun.png",
    "CZ75-Auto | Yellow Jacket": "assets/cases/falchion-case/weapons/012_CZ75-Auto_Yellow_Jacket.png",
    "MP7 | Nemesis": "assets/cases/falchion-case/weapons/013_MP7_Nemesis.png",
    "SG 553 | Cyrex": "assets/cases/falchion-case/weapons/014_SG_553_Cyrex.png",
    "AK-47 | Aquamarine Revenge": "assets/cases/falchion-case/weapons/015_AK-47_Aquamarine_Revenge.png",
    "AWP | Hyper Beast": "assets/cases/falchion-case/weapons/016_AWP_Hyper_Beast.png",
    "★ Falchion Knife": "assets/cases/falchion-case/weapons/017_%E2%98%85_Falchion_Knife.png",
    "★ Falchion Knife | Fade": "assets/cases/falchion-case/weapons/018_%E2%98%85_Falchion_Knife_Fade.png",
    "★ Falchion Knife | Crimson Web": "assets/cases/falchion-case/weapons/019_%E2%98%85_Falchion_Knife_Crimson_Web.png",
    "★ Falchion Knife | Slaughter": "assets/cases/falchion-case/weapons/020_%E2%98%85_Falchion_Knife_Slaughter.png",
    "★ Falchion Knife | Case Hardened": "assets/cases/falchion-case/weapons/021_%E2%98%85_Falchion_Knife_Case_Hardened.png",
    "★ Falchion Knife | Urban Masked": "assets/cases/falchion-case/weapons/022_%E2%98%85_Falchion_Knife_Urban_Masked.png",
    "★ Falchion Knife | Blue Steel": "assets/cases/falchion-case/weapons/023_%E2%98%85_Falchion_Knife_Blue_Steel.png",
    "★ Falchion Knife | Night": "assets/cases/falchion-case/weapons/024_%E2%98%85_Falchion_Knife_Night.png",
    "★ Falchion Knife | Stained": "assets/cases/falchion-case/weapons/025_%E2%98%85_Falchion_Knife_Stained.png",
    "★ Falchion Knife | Forest DDPAT": "assets/cases/falchion-case/weapons/026_%E2%98%85_Falchion_Knife_Forest_DDPAT.png",
    "★ Falchion Knife | Boreal Forest": "assets/cases/falchion-case/weapons/027_%E2%98%85_Falchion_Knife_Boreal_Forest.png",
    "★ Falchion Knife | Scorched": "assets/cases/falchion-case/weapons/028_%E2%98%85_Falchion_Knife_Scorched.png",
    "★ Falchion Knife | Safari Mesh": "assets/cases/falchion-case/weapons/029_%E2%98%85_Falchion_Knife_Safari_Mesh.png",
    "PP-Bizon | Photic Zone": "assets/cases/operation-wildfire-case/weapons/001_PP-Bizon_Photic_Zone.png",
    "Dual Berettas | Cartel": "assets/cases/operation-wildfire-case/weapons/002_Dual_Berettas_Cartel.png",
    "MAC-10 | Lapis Gator": "assets/cases/operation-wildfire-case/weapons/003_MAC-10_Lapis_Gator.png",
    "SSG 08 | Necropos": "assets/cases/operation-wildfire-case/weapons/004_SSG_08_Necropos.png",
    "Tec-9 | Jambiya": "assets/cases/operation-wildfire-case/weapons/005_Tec-9_Jambiya.png",
    "USP-S | Lead Conduit": "assets/cases/operation-wildfire-case/weapons/006_USP-S_Lead_Conduit.png",
    "FAMAS | Valence": "assets/cases/operation-wildfire-case/weapons/007_FAMAS_Valence.png",
    "Five-SeveN | Triumvirate": "assets/cases/operation-wildfire-case/weapons/008_Five-SeveN_Triumvirate.png",
    "Glock-18 | Royal Legion": "assets/cases/operation-wildfire-case/weapons/009_Glock-18_Royal_Legion.png",
    "MAG-7 | Praetorian": "assets/cases/operation-wildfire-case/weapons/010_MAG-7_Praetorian.png",
    "MP7 | Impire": "assets/cases/operation-wildfire-case/weapons/011_MP7_Impire.png",
    "AWP | Elite Build": "assets/cases/operation-wildfire-case/weapons/012_AWP_Elite_Build.png",
    "Desert Eagle | Kumicho Dragon": "assets/cases/operation-wildfire-case/weapons/013_Desert_Eagle_Kumicho_Dragon.png",
    "Nova | Hyper Beast": "assets/cases/operation-wildfire-case/weapons/014_Nova_Hyper_Beast.png",
    "AK-47 | Fuel Injector": "assets/cases/operation-wildfire-case/weapons/015_AK-47_Fuel_Injector.png",
    "M4A4 | The Battlestar": "assets/cases/operation-wildfire-case/weapons/016_M4A4_The_Battlestar.png",
    "★ Bowie Knife": "assets/cases/operation-wildfire-case/weapons/017_%E2%98%85_Bowie_Knife.png",
    "★ Bowie Knife | Fade": "assets/cases/operation-wildfire-case/weapons/018_%E2%98%85_Bowie_Knife_Fade.png",
    "★ Bowie Knife | Crimson Web": "assets/cases/operation-wildfire-case/weapons/019_%E2%98%85_Bowie_Knife_Crimson_Web.png",
    "★ Bowie Knife | Slaughter": "assets/cases/operation-wildfire-case/weapons/020_%E2%98%85_Bowie_Knife_Slaughter.png",
    "★ Bowie Knife | Case Hardened": "assets/cases/operation-wildfire-case/weapons/021_%E2%98%85_Bowie_Knife_Case_Hardened.png",
    "★ Bowie Knife | Urban Masked": "assets/cases/operation-wildfire-case/weapons/022_%E2%98%85_Bowie_Knife_Urban_Masked.png",
    "★ Bowie Knife | Blue Steel": "assets/cases/operation-wildfire-case/weapons/023_%E2%98%85_Bowie_Knife_Blue_Steel.png",
    "★ Bowie Knife | Night": "assets/cases/operation-wildfire-case/weapons/024_%E2%98%85_Bowie_Knife_Night.png",
    "★ Bowie Knife | Stained": "assets/cases/operation-wildfire-case/weapons/025_%E2%98%85_Bowie_Knife_Stained.png",
    "★ Bowie Knife | Forest DDPAT": "assets/cases/operation-wildfire-case/weapons/026_%E2%98%85_Bowie_Knife_Forest_DDPAT.png",
    "★ Bowie Knife | Boreal Forest": "assets/cases/operation-wildfire-case/weapons/027_%E2%98%85_Bowie_Knife_Boreal_Forest.png",
    "★ Bowie Knife | Scorched": "assets/cases/operation-wildfire-case/weapons/028_%E2%98%85_Bowie_Knife_Scorched.png",
    "★ Bowie Knife | Safari Mesh": "assets/cases/operation-wildfire-case/weapons/029_%E2%98%85_Bowie_Knife_Safari_Mesh.png",
    "MP7 | Urban Hazard": "assets/cases/operation-breakout-weapon-case/weapons/001_MP7_Urban_Hazard.png",
    "Negev | Desert-Strike": "assets/cases/operation-breakout-weapon-case/weapons/002_Negev_Desert-Strike.png",
    "P2000 | Ivory": "assets/cases/operation-breakout-weapon-case/weapons/003_P2000_Ivory.png",
    "SSG 08 | Abyss": "assets/cases/operation-breakout-weapon-case/weapons/004_SSG_08_Abyss.png",
    "UMP-45 | Labyrinth": "assets/cases/operation-breakout-weapon-case/weapons/005_UMP-45_Labyrinth.png",
    "PP-Bizon | Osiris": "assets/cases/operation-breakout-weapon-case/weapons/006_PP-Bizon_Osiris.png",
    "CZ75-Auto | Tigris": "assets/cases/operation-breakout-weapon-case/weapons/007_CZ75-Auto_Tigris.png",
    "Nova | Koi": "assets/cases/operation-breakout-weapon-case/weapons/008_Nova_Koi.png",
    "P250 | Supernova": "assets/cases/operation-breakout-weapon-case/weapons/009_P250_Supernova.png",
    "Desert Eagle | Conspiracy": "assets/cases/operation-breakout-weapon-case/weapons/010_Desert_Eagle_Conspiracy.png",
    "Five-SeveN | Fowl Play": "assets/cases/operation-breakout-weapon-case/weapons/011_Five-SeveN_Fowl_Play.png",
    "Glock-18 | Water Elemental": "assets/cases/operation-breakout-weapon-case/weapons/012_Glock-18_Water_Elemental.png",
    "P90 | Asiimov": "assets/cases/operation-breakout-weapon-case/weapons/013_P90_Asiimov.png",
    "M4A1-S | Cyrex": "assets/cases/operation-breakout-weapon-case/weapons/014_M4A1-S_Cyrex.png",
    "★ Butterfly Knife": "assets/cases/operation-breakout-weapon-case/weapons/015_%E2%98%85_Butterfly_Knife.png",
    "★ Butterfly Knife | Fade": "assets/cases/operation-breakout-weapon-case/weapons/016_%E2%98%85_Butterfly_Knife_Fade.png",
    "★ Butterfly Knife | Crimson Web": "assets/cases/operation-breakout-weapon-case/weapons/017_%E2%98%85_Butterfly_Knife_Crimson_Web.png",
    "★ Butterfly Knife | Slaughter": "assets/cases/operation-breakout-weapon-case/weapons/018_%E2%98%85_Butterfly_Knife_Slaughter.png",
    "★ Butterfly Knife | Case Hardened": "assets/cases/operation-breakout-weapon-case/weapons/019_%E2%98%85_Butterfly_Knife_Case_Hardened.png",
    "★ Butterfly Knife | Urban Masked": "assets/cases/operation-breakout-weapon-case/weapons/020_%E2%98%85_Butterfly_Knife_Urban_Masked.png",
    "★ Butterfly Knife | Blue Steel": "assets/cases/operation-breakout-weapon-case/weapons/021_%E2%98%85_Butterfly_Knife_Blue_Steel.png",
    "★ Butterfly Knife | Night": "assets/cases/operation-breakout-weapon-case/weapons/022_%E2%98%85_Butterfly_Knife_Night.png",
    "★ Butterfly Knife | Stained": "assets/cases/operation-breakout-weapon-case/weapons/023_%E2%98%85_Butterfly_Knife_Stained.png",
    "★ Butterfly Knife | Forest DDPAT": "assets/cases/operation-breakout-weapon-case/weapons/024_%E2%98%85_Butterfly_Knife_Forest_DDPAT.png",
    "★ Butterfly Knife | Boreal Forest": "assets/cases/operation-breakout-weapon-case/weapons/025_%E2%98%85_Butterfly_Knife_Boreal_Forest.png",
    "★ Butterfly Knife | Scorched": "assets/cases/operation-breakout-weapon-case/weapons/026_%E2%98%85_Butterfly_Knife_Scorched.png",
    "★ Butterfly Knife | Safari Mesh": "assets/cases/operation-breakout-weapon-case/weapons/027_%E2%98%85_Butterfly_Knife_Safari_Mesh.png",
    "G3SG1 | Murky": "assets/cases/operation-vanguard-weapon-case/weapons/001_G3SG1_Murky.png",
    "MAG-7 | Firestarter": "assets/cases/operation-vanguard-weapon-case/weapons/002_MAG-7_Firestarter.png",
    "MP9 | Dart": "assets/cases/operation-vanguard-weapon-case/weapons/003_MP9_Dart.png",
    "Five-SeveN | Urban Hazard": "assets/cases/operation-vanguard-weapon-case/weapons/004_Five-SeveN_Urban_Hazard.png",
    "UMP-45 | Delusion": "assets/cases/operation-vanguard-weapon-case/weapons/005_UMP-45_Delusion.png",
    "Glock-18 | Grinder": "assets/cases/operation-vanguard-weapon-case/weapons/006_Glock-18_Grinder.png",
    "M4A1-S | Basilisk": "assets/cases/operation-vanguard-weapon-case/weapons/007_M4A1-S_Basilisk.png",
    "M4A4 | Griffin": "assets/cases/operation-vanguard-weapon-case/weapons/008_M4A4_Griffin.png",
    "Sawed-Off | Highwayman": "assets/cases/operation-vanguard-weapon-case/weapons/009_Sawed-Off_Highwayman.png",
    "P250 | Cartel": "assets/cases/operation-vanguard-weapon-case/weapons/010_P250_Cartel.png",
    "SCAR-20 | Cardiac": "assets/cases/operation-vanguard-weapon-case/weapons/011_SCAR-20_Cardiac.png",
    "XM1014 | Tranquility": "assets/cases/operation-vanguard-weapon-case/weapons/012_XM1014_Tranquility.png",
    "AK-47 | Wasteland Rebel": "assets/cases/operation-vanguard-weapon-case/weapons/013_AK-47_Wasteland_Rebel.png",
    "P2000 | Fire Elemental": "assets/cases/operation-vanguard-weapon-case/weapons/014_P2000_Fire_Elemental.png",
    "★ Bayonet": "assets/cases/operation-phoenix-weapon-case/weapons/014_%E2%98%85_Bayonet.png",
    "★ Bayonet | Fade": "assets/cases/operation-phoenix-weapon-case/weapons/015_%E2%98%85_Bayonet_Fade.png",
    "★ Bayonet | Slaughter": "assets/cases/operation-phoenix-weapon-case/weapons/016_%E2%98%85_Bayonet_Slaughter.png",
    "★ Bayonet | Case Hardened": "assets/cases/operation-phoenix-weapon-case/weapons/017_%E2%98%85_Bayonet_Case_Hardened.png",
    "★ Bayonet | Night": "assets/cases/operation-phoenix-weapon-case/weapons/018_%E2%98%85_Bayonet_Night.png",
    "★ Bayonet | Blue Steel": "assets/cases/operation-phoenix-weapon-case/weapons/019_%E2%98%85_Bayonet_Blue_Steel.png",
    "★ Bayonet | Crimson Web": "assets/cases/operation-phoenix-weapon-case/weapons/020_%E2%98%85_Bayonet_Crimson_Web.png",
    "★ Bayonet | Stained": "assets/cases/operation-phoenix-weapon-case/weapons/021_%E2%98%85_Bayonet_Stained.png",
    "★ Bayonet | Scorched": "assets/cases/operation-phoenix-weapon-case/weapons/022_%E2%98%85_Bayonet_Scorched.png",
    "★ Bayonet | Safari Mesh": "assets/cases/operation-phoenix-weapon-case/weapons/023_%E2%98%85_Bayonet_Safari_Mesh.png",
    "★ Bayonet | Boreal Forest": "assets/cases/operation-phoenix-weapon-case/weapons/024_%E2%98%85_Bayonet_Boreal_Forest.png",
    "★ Bayonet | Urban Masked": "assets/cases/operation-phoenix-weapon-case/weapons/025_%E2%98%85_Bayonet_Urban_Masked.png",
    "★ Bayonet | Forest DDPAT": "assets/cases/operation-phoenix-weapon-case/weapons/026_%E2%98%85_Bayonet_Forest_DDPAT.png",
    "★ Flip Knife": "assets/cases/operation-phoenix-weapon-case/weapons/027_%E2%98%85_Flip_Knife.png",
    "★ Flip Knife | Fade": "assets/cases/operation-phoenix-weapon-case/weapons/028_%E2%98%85_Flip_Knife_Fade.png",
    "★ Flip Knife | Slaughter": "assets/cases/operation-phoenix-weapon-case/weapons/029_%E2%98%85_Flip_Knife_Slaughter.png",
    "★ Flip Knife | Case Hardened": "assets/cases/operation-phoenix-weapon-case/weapons/030_%E2%98%85_Flip_Knife_Case_Hardened.png",
    "★ Flip Knife | Night": "assets/cases/operation-phoenix-weapon-case/weapons/031_%E2%98%85_Flip_Knife_Night.png",
    "★ Flip Knife | Blue Steel": "assets/cases/operation-phoenix-weapon-case/weapons/032_%E2%98%85_Flip_Knife_Blue_Steel.png",
    "★ Flip Knife | Crimson Web": "assets/cases/operation-phoenix-weapon-case/weapons/033_%E2%98%85_Flip_Knife_Crimson_Web.png",
    "★ Flip Knife | Stained": "assets/cases/operation-phoenix-weapon-case/weapons/034_%E2%98%85_Flip_Knife_Stained.png",
    "★ Flip Knife | Scorched": "assets/cases/operation-phoenix-weapon-case/weapons/035_%E2%98%85_Flip_Knife_Scorched.png",
    "★ Flip Knife | Safari Mesh": "assets/cases/operation-phoenix-weapon-case/weapons/036_%E2%98%85_Flip_Knife_Safari_Mesh.png",
    "★ Flip Knife | Boreal Forest": "assets/cases/operation-phoenix-weapon-case/weapons/037_%E2%98%85_Flip_Knife_Boreal_Forest.png",
    "★ Flip Knife | Urban Masked": "assets/cases/operation-phoenix-weapon-case/weapons/038_%E2%98%85_Flip_Knife_Urban_Masked.png",
    "★ Flip Knife | Forest DDPAT": "assets/cases/operation-phoenix-weapon-case/weapons/039_%E2%98%85_Flip_Knife_Forest_DDPAT.png",
    "★ Gut Knife": "assets/cases/operation-phoenix-weapon-case/weapons/040_%E2%98%85_Gut_Knife.png",
    "★ Gut Knife | Fade": "assets/cases/operation-phoenix-weapon-case/weapons/041_%E2%98%85_Gut_Knife_Fade.png",
    "★ Gut Knife | Slaughter": "assets/cases/operation-phoenix-weapon-case/weapons/042_%E2%98%85_Gut_Knife_Slaughter.png",
    "★ Gut Knife | Case Hardened": "assets/cases/operation-phoenix-weapon-case/weapons/043_%E2%98%85_Gut_Knife_Case_Hardened.png",
    "★ Gut Knife | Night": "assets/cases/operation-phoenix-weapon-case/weapons/044_%E2%98%85_Gut_Knife_Night.png",
    "★ Gut Knife | Blue Steel": "assets/cases/operation-phoenix-weapon-case/weapons/045_%E2%98%85_Gut_Knife_Blue_Steel.png",
    "★ Gut Knife | Crimson Web": "assets/cases/operation-phoenix-weapon-case/weapons/046_%E2%98%85_Gut_Knife_Crimson_Web.png",
    "★ Gut Knife | Stained": "assets/cases/operation-phoenix-weapon-case/weapons/047_%E2%98%85_Gut_Knife_Stained.png",
    "★ Gut Knife | Scorched": "assets/cases/operation-phoenix-weapon-case/weapons/048_%E2%98%85_Gut_Knife_Scorched.png",
    "★ Gut Knife | Safari Mesh": "assets/cases/operation-phoenix-weapon-case/weapons/049_%E2%98%85_Gut_Knife_Safari_Mesh.png",
    "★ Gut Knife | Boreal Forest": "assets/cases/operation-phoenix-weapon-case/weapons/050_%E2%98%85_Gut_Knife_Boreal_Forest.png",
    "★ Gut Knife | Urban Masked": "assets/cases/operation-phoenix-weapon-case/weapons/051_%E2%98%85_Gut_Knife_Urban_Masked.png",
    "★ Gut Knife | Forest DDPAT": "assets/cases/operation-phoenix-weapon-case/weapons/052_%E2%98%85_Gut_Knife_Forest_DDPAT.png",
    "★ Karambit": "assets/cases/operation-phoenix-weapon-case/weapons/053_%E2%98%85_Karambit.png",
    "★ Karambit | Fade": "assets/cases/operation-phoenix-weapon-case/weapons/054_%E2%98%85_Karambit_Fade.png",
    "★ Karambit | Slaughter": "assets/cases/operation-phoenix-weapon-case/weapons/055_%E2%98%85_Karambit_Slaughter.png",
    "★ Karambit | Case Hardened": "assets/cases/operation-phoenix-weapon-case/weapons/056_%E2%98%85_Karambit_Case_Hardened.png",
    "★ Karambit | Night": "assets/cases/operation-phoenix-weapon-case/weapons/057_%E2%98%85_Karambit_Night.png",
    "★ Karambit | Blue Steel": "assets/cases/operation-phoenix-weapon-case/weapons/058_%E2%98%85_Karambit_Blue_Steel.png",
    "★ Karambit | Crimson Web": "assets/cases/operation-phoenix-weapon-case/weapons/059_%E2%98%85_Karambit_Crimson_Web.png",
    "★ Karambit | Stained": "assets/cases/operation-phoenix-weapon-case/weapons/060_%E2%98%85_Karambit_Stained.png",
    "★ Karambit | Scorched": "assets/cases/operation-phoenix-weapon-case/weapons/061_%E2%98%85_Karambit_Scorched.png",
    "★ Karambit | Safari Mesh": "assets/cases/operation-phoenix-weapon-case/weapons/062_%E2%98%85_Karambit_Safari_Mesh.png",
    "★ Karambit | Boreal Forest": "assets/cases/operation-phoenix-weapon-case/weapons/063_%E2%98%85_Karambit_Boreal_Forest.png",
    "★ Karambit | Urban Masked": "assets/cases/operation-phoenix-weapon-case/weapons/064_%E2%98%85_Karambit_Urban_Masked.png",
    "★ Karambit | Forest DDPAT": "assets/cases/operation-phoenix-weapon-case/weapons/065_%E2%98%85_Karambit_Forest_DDPAT.png",
    "★ M9 Bayonet": "assets/cases/operation-phoenix-weapon-case/weapons/066_%E2%98%85_M9_Bayonet.png",
    "★ M9 Bayonet | Fade": "assets/cases/operation-phoenix-weapon-case/weapons/067_%E2%98%85_M9_Bayonet_Fade.png",
    "★ M9 Bayonet | Slaughter": "assets/cases/operation-phoenix-weapon-case/weapons/068_%E2%98%85_M9_Bayonet_Slaughter.png",
    "★ M9 Bayonet | Case Hardened": "assets/cases/operation-phoenix-weapon-case/weapons/069_%E2%98%85_M9_Bayonet_Case_Hardened.png",
    "★ M9 Bayonet | Night": "assets/cases/operation-phoenix-weapon-case/weapons/070_%E2%98%85_M9_Bayonet_Night.png",
    "★ M9 Bayonet | Blue Steel": "assets/cases/operation-phoenix-weapon-case/weapons/071_%E2%98%85_M9_Bayonet_Blue_Steel.png",
    "★ M9 Bayonet | Crimson Web": "assets/cases/operation-phoenix-weapon-case/weapons/072_%E2%98%85_M9_Bayonet_Crimson_Web.png",
    "★ M9 Bayonet | Stained": "assets/cases/operation-phoenix-weapon-case/weapons/073_%E2%98%85_M9_Bayonet_Stained.png",
    "★ M9 Bayonet | Scorched": "assets/cases/operation-phoenix-weapon-case/weapons/074_%E2%98%85_M9_Bayonet_Scorched.png",
    "★ M9 Bayonet | Safari Mesh": "assets/cases/operation-phoenix-weapon-case/weapons/075_%E2%98%85_M9_Bayonet_Safari_Mesh.png",
    "★ M9 Bayonet | Boreal Forest": "assets/cases/operation-phoenix-weapon-case/weapons/076_%E2%98%85_M9_Bayonet_Boreal_Forest.png",
    "★ M9 Bayonet | Urban Masked": "assets/cases/operation-phoenix-weapon-case/weapons/077_%E2%98%85_M9_Bayonet_Urban_Masked.png",
    "★ M9 Bayonet | Forest DDPAT": "assets/cases/operation-phoenix-weapon-case/weapons/078_%E2%98%85_M9_Bayonet_Forest_DDPAT.png",
    "UMP-45 | Corporal": "assets/cases/operation-phoenix-weapon-case/weapons/001_UMP-45_Corporal.png",
    "Negev | Terrain": "assets/cases/operation-phoenix-weapon-case/weapons/002_Negev_Terrain.png",
    "Tec-9 | Sandstorm": "assets/cases/operation-phoenix-weapon-case/weapons/003_Tec-9_Sandstorm.png",
    "MAG-7 | Heaven Guard": "assets/cases/operation-phoenix-weapon-case/weapons/004_MAG-7_Heaven_Guard.png",
    "MAC-10 | Heat": "assets/cases/operation-phoenix-weapon-case/weapons/005_MAC-10_Heat.png",
    "SG 553 | Pulse": "assets/cases/operation-phoenix-weapon-case/weapons/006_SG_553_Pulse.png",
    "FAMAS | Sergeant": "assets/cases/operation-phoenix-weapon-case/weapons/007_FAMAS_Sergeant.png",
    "USP-S | Guardian": "assets/cases/operation-phoenix-weapon-case/weapons/008_USP-S_Guardian.png",
    "AK-47 | Redline": "assets/cases/operation-phoenix-weapon-case/weapons/009_AK-47_Redline.png",
    "P90 | Trigon": "assets/cases/operation-phoenix-weapon-case/weapons/010_P90_Trigon.png",
    "Nova | Antique": "assets/cases/operation-phoenix-weapon-case/weapons/011_Nova_Antique.png",
    "AWP | Asiimov": "assets/cases/operation-phoenix-weapon-case/weapons/012_AWP_Asiimov.png",
    "AUG | Chameleon": "assets/cases/operation-phoenix-weapon-case/weapons/013_AUG_Chameleon.png",
    "Tec-9 | Isaac": "assets/cases/huntsman-weapon-case/weapons/001_Tec-9_Isaac.png",
    "SSG 08 | Slashed": "assets/cases/huntsman-weapon-case/weapons/002_SSG_08_Slashed.png",
    "Galil AR | Kami": "assets/cases/huntsman-weapon-case/weapons/003_Galil_AR_Kami.png",
    "CZ75-Auto | Twist": "assets/cases/huntsman-weapon-case/weapons/004_CZ75-Auto_Twist.png",
    "P90 | Module": "assets/cases/huntsman-weapon-case/weapons/005_P90_Module.png",
    "P2000 | Pulse": "assets/cases/huntsman-weapon-case/weapons/006_P2000_Pulse.png",
    "AUG | Torque": "assets/cases/huntsman-weapon-case/weapons/007_AUG_Torque.png",
    "PP-Bizon | Antique": "assets/cases/huntsman-weapon-case/weapons/008_PP-Bizon_Antique.png",
    "XM1014 | Heaven Guard": "assets/cases/huntsman-weapon-case/weapons/009_XM1014_Heaven_Guard.png",
    "MAC-10 | Tatter": "assets/cases/huntsman-weapon-case/weapons/010_MAC-10_Tatter.png",
    "M4A1-S | Atomic Alloy": "assets/cases/huntsman-weapon-case/weapons/011_M4A1-S_Atomic_Alloy.png",
    "SCAR-20 | Cyrex": "assets/cases/huntsman-weapon-case/weapons/012_SCAR-20_Cyrex.png",
    "USP-S | Caiman": "assets/cases/huntsman-weapon-case/weapons/013_USP-S_Caiman.png",
    "AK-47 | Vulcan": "assets/cases/huntsman-weapon-case/weapons/014_AK-47_Vulcan.png",
    "M4A4 | Desert-Strike": "assets/cases/huntsman-weapon-case/weapons/015_M4A4_Desert-Strike.png",
    "★ Huntsman Knife": "assets/cases/huntsman-weapon-case/weapons/016_%E2%98%85_Huntsman_Knife.png",
    "★ Huntsman Knife | Fade": "assets/cases/huntsman-weapon-case/weapons/017_%E2%98%85_Huntsman_Knife_Fade.png",
    "★ Huntsman Knife | Crimson Web": "assets/cases/huntsman-weapon-case/weapons/018_%E2%98%85_Huntsman_Knife_Crimson_Web.png",
    "★ Huntsman Knife | Slaughter": "assets/cases/huntsman-weapon-case/weapons/019_%E2%98%85_Huntsman_Knife_Slaughter.png",
    "★ Huntsman Knife | Case Hardened": "assets/cases/huntsman-weapon-case/weapons/020_%E2%98%85_Huntsman_Knife_Case_Hardened.png",
    "★ Huntsman Knife | Urban Masked": "assets/cases/huntsman-weapon-case/weapons/021_%E2%98%85_Huntsman_Knife_Urban_Masked.png",
    "★ Huntsman Knife | Blue Steel": "assets/cases/huntsman-weapon-case/weapons/022_%E2%98%85_Huntsman_Knife_Blue_Steel.png",
    "★ Huntsman Knife | Night": "assets/cases/huntsman-weapon-case/weapons/023_%E2%98%85_Huntsman_Knife_Night.png",
    "★ Huntsman Knife | Stained": "assets/cases/huntsman-weapon-case/weapons/024_%E2%98%85_Huntsman_Knife_Stained.png",
    "★ Huntsman Knife | Forest DDPAT": "assets/cases/huntsman-weapon-case/weapons/025_%E2%98%85_Huntsman_Knife_Forest_DDPAT.png",
    "★ Huntsman Knife | Boreal Forest": "assets/cases/huntsman-weapon-case/weapons/026_%E2%98%85_Huntsman_Knife_Boreal_Forest.png",
    "★ Huntsman Knife | Scorched": "assets/cases/huntsman-weapon-case/weapons/027_%E2%98%85_Huntsman_Knife_Scorched.png",
    "★ Huntsman Knife | Safari Mesh": "assets/cases/huntsman-weapon-case/weapons/028_%E2%98%85_Huntsman_Knife_Safari_Mesh.png"
  }
};
